### PR TITLE
Add port check in cronjob

### PR DESCRIPTION
**Pull request by enoch85**
Question is, should we add this and potentially send out notifications every day, or should we just remind the user with a `msg_box`that port 80 needs to be open?

### CODE REVIEW

**Comment by szaimen** [comment]
I am voting for both, so that if you run it manually, it will remind you, and if it isn't open, you get informed by the nexcloud notification.

**Comment by enoch85** [comment]
> you get informed by the nexcloud notification.

Problem is that the check will fail to see if the port is open, and should those users get spammed every day with a notification, even if the port actually is open?

**Comment by szaimen** [comment]
You are right. So then maybe just inform the user if the cert renewal wasn't successful over notify_admin_gui and say that it could be caused by port 80 not beeing open?
But it seems like xou already planned to do it this way...
Of course we could store the info that the notification was already sent in the scriot itself, a bit like I am planning to do it https://github.com/nextcloud/vm/pull/1141 ...

**Comment by szaimen** [comment]
But actually I would always report over notifY_admin_gui if a cert renewal wasn't successfull. And just say in there that it could be caused by port 80 not being open...

**Comment by szaimen** [comment]
I mean what would you say how many notifications are okay? Every day for 7 days? Or just every second day? Or what would be the best in your opinion?

**Comment by enoch85** [comment]
No, let's close this. I don't want to spam users with notifications. Will make a new PR with a msg_box instead.

**Pull request closed without merging**
