### PR TITLE
[WIP] change to mariadb

### PR DESCRIPTION
**Pull request by enoch85**
Part fix for https://github.com/nextcloud/vm/issues/262

### CODE REVIEW

**Comment by enoch85** [comment]
cc @maxibanki 

This is a start at least. Please test and confirm that everything is working.

**Comment by ezraholm50** [comment]
Curious about the switch to mariadb? This is good for the Nextberry project, will be able to use the latest version instead of Mysql 5.5

**Comment by maxibanki** [comment]
Great, but currently I don't have much time, it's already on my TODO to implement this. :/

**Comment by enoch85** [comment]
@mabkenar I'll merge this if you approve it, and then you can improve it even more if you'd like. I've already tested it and it works, just need a confirmation. :)

>  it's already on my TODO to implement this. :/

That's a good thing then. Please focus with Nginx and the other stuff once this is in.

**Comment by enoch85** [comment]
OK, this is good now. Tested against current VM as well.

**Pull request merged**
