### PR TITLE
Add another flag to the install-script

### PR DESCRIPTION
**Pull request by szaimen**
As the title says
This is for what I need #1644 (So #1644 would need to get merged first)

@enoch85 What do you think? I really want this!

### CODE REVIEW

**Comment by enoch85** [comment]
No, we will never add the not supported stiff into any of the released scripts.

**Comment by enoch85** [comment]
Thanks for the effort though.

**Comment by szaimen** [comment]
Too bad :/
I thought this was finally a solution you would be okay with ☹️

**Comment by enoch85** [comment]
Sorry

**Pull request closed without merging**
