### PR TITLE
allow to use the LVM configuration as it was setup by the installer

### PR DESCRIPTION
**Pull request by szaimen**
To be able to use features like lvm snapshots, it is incredibly useful to have the choice to not run the resize2fs comand. 

I hope this way it is okay (you just hit enter to continue as usual)

### CODE REVIEW

**Comment by enoch85** [comment]
While digging into LVM, maybe you could have a look at this? https://github.com/nextcloud/vm/issues/1481

Are you saying that you can't do snapshots if you do `rezie2fs`?

**Comment by szaimen** [comment]
> While digging into LVM, maybe you could have a look at this? #1481

Maybe after this, yes. The thing is, I don't completely understand what the guy requested in this issue and the link doesn't fit, either?

> Are you saying that you can't do snapshots if you do `rezie2fs`?

Yes. I cannot create LVM-snapshots if I do resize2fs. ZFS snapshots still work, though.

**Comment by enoch85** [comment]
You know that this will give you a full sized PV, but it won't give you the full sized LV, right?

**Comment by szaimen** [comment]
> You know that this will give you a full sized PV, but it won't give you the full sized LV, right?

Yes of course 👍

**Comment by enoch85** [comment]
Sure, why not.

**Pull request merged**
