### PR TITLE
Update Main Websocket error for docker image

### PR DESCRIPTION
**Pull request by Ark74**
See more: https://help.nextcloud.com/t/updated-collabora-now-unable-to-open-documents/4179/15

### CODE REVIEW

**Comment by enoch85** [comment]
@Ark74 Thanks for this PR! Have you tested the script? Does it work out of the box?

**Comment by Ark74** [comment]
Sadly, i can't get it running out of the box.
I have a ssl wildcard that i wanna use, so i'm not running the script per se, i'm following it.

This is my second test, the first one, this PR  got me one step closer ( i was able to load the interface)
This is my second try but now i can't get pass through 

> Access Forbidden

Any suggestion on what to check?
The enviroment is the one for the VM
* Ubuntu16.04
* Apache
* Nextcloud
* Docker

**Comment by Ark74** [comment]
Finally it got it working.
The issue is to use:
`https://cloud.domain.com/`
(no port defined)
On the Collabora Settings URL

**Comment by enoch85** [comment]
Please have a look at this PR and make your changes there instead: https://github.com/nextcloud/vm/pull/40

I'll give you access to this repo.

**Pull request closed without merging**
