### PR TITLE
smbserver - add a fixed netbios name

### PR DESCRIPTION
**Pull request by szaimen**
This is needed to be able to connect always using `nextcloud` as server name.

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
This is ready :)

**Comment by enoch85** [comment]
Would it be possible to add the hostname instead? `$(hosname)`

**Comment by szaimen** [comment]
> Would it be possible to add the hostname instead? `$(hosname)`

The hostname already works in my testing. So you are with this fix able to access the smb server using the hostname and nextcloud as server name.

This fix is necessary since the hostname is proven to change during the activate tls script and accessing the smb server using the hostname is thus not stable because it can change

**Comment by szaimen** [comment]
Anything missing here?

**Pull request merged**
