### PR TITLE
Update on CODE 2.0

### PR DESCRIPTION
**Pull request by Ark74**
Check this https://www.collaboraoffice.com/community-en/code-2-0-updates-2/
Settings has changed.

### CODE REVIEW

**Comment by ezraholm50** [comment]
Could you explain the changes please

**Comment by enoch85** [comment]
Thanks! The script does not still work though. 

Can you please help us out here @Ark74 as it will be live in Nextcloud 11.0.1.

**Comment by Ark74** [comment]
Which part isn't working?

**Comment by enoch85** [comment]
@Ark74 Test the script, I can't get it to work flawlessly anyway. Have you tested it? If not, please do.

Thanks!

**Comment by ezraholm50** [comment]
Thanks for the link. As of next week I can start testing.

**Pull request merged**
