### PR TITLE
fix zero byte files

### LINKED ISSUE #2123: SetEnv proxy-sendcl 1
https://github.com/nextcloud/vm/issues/1534#issuecomment-954613649

### PR DESCRIPTION
**Pull request by szaimen**
Close #2123

@Zealot2000 did I understand correctly that you simply did this?

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by Zealot2000** [comment]
@szaimen Two actions are needed for this to work:
- Setting "SetEnv proxy-sendcl 1"
- Updating Apache to 2.4.47 or newer

(see https://bz.apache.org/bugzilla/show_bug.cgi?id=57087)

**Comment by szaimen** [comment]
Thanks for the heads-up!

Since we are not going to update apache from other sources, I guess this will only be useful with ubuntu 22.04. So I guess @enoch85 should decide if we merge this now or wait for the switch to ubuntu 22.04...

**Comment by enoch85** [comment]
@szaimen  Thanks!

Add a check for Ubuntu 22.04 so that we can merge now. 👌🏻

**Comment by szaimen** [comment]
@enoch85 done 👍

**Comment by enoch85** [comment]
@szaimen Thanks, but please use the `version` check instead.

**Comment by szaimen** [comment]
> @szaimen Thanks, but please use the `version` check instead.

do you have an example how it should look like in this case?

**Comment by enoch85** [comment]
@szaimen 

https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-tls.sh#L118-L122

**Comment by enoch85** [comment]
@szaimen Can you please add the same fix in `nextcloud_install_production`?

**Comment by szaimen** [comment]
@enoch85 do you know if it fixes the bug on Ubuntu 22.04? I was not able to confirm this yet...

**Comment by enoch85** [comment]
No, I don't know. Haven't tested this specifically

**Pull request merged**
