### PR TITLE
Disable hibernation

### PR DESCRIPTION
**Pull request by szaimen**
Imo, hibernation doesn't make sense, does it?

We could alternatively ask the user...

### CODE REVIEW

**Comment by enoch85** [comment]
Makes sense.

Thanks!

**Comment by enoch85** [comment]
Question is, does this apply to servers? 

Do you have a source?

**Comment by szaimen** [comment]
> Question is, does this apply to servers?
> 
> Do you have a source?

I have already tested this successfully on a test machine.

**Comment by enoch85** [comment]
> I have already tested this successfully on a test server

That's great! But, if I chose to leave my server on 24/7 it would never hibernate anyway, that's why I'm asking if this is really needed?

**Comment by enoch85** [comment]
Hmm, seems like it could happen in some rare cases: https://www.unixtutorial.org/disable-sleep-on-ubuntu-server/

**Pull request merged**
