### PR TITLE
update snap to latest

### PR DESCRIPTION
**Pull request by johnfelipe**

### CODE REVIEW

**Comment by enoch85** [comment]
Great! Have you tested this? What are the benefits? Does it solve any problem?

**Comment by enoch85** [comment]
Ping @johnfelipe 

Using `--edge` could be unstable, so that's why I'm asking if it makes any improvements, or fix any issues?

**Comment by enoch85** [comment]
ping @johnfelipe Can you answer above questions please?

**Comment by johnfelipe** [comment]
Great! Have you tested this? YES
What are the benefits? I can use in wifi and 4g network in my office 
Does it solve any problem? for moment solve all issue with spreedme and coturn

**Comment by enoch85** [comment]
@johnfelipe Did you notice it was unstable?

Also, which specific issues did you have prior to this fix?

**Comment by johnfelipe** [comment]
Did you notice it was unstable? for me wasn´t

Also, which specific issues did you have prior to this fix? is not issues because is working for me in ubuntu 16 own server and digitalocean, suggest change -edge parameter.

**Comment by enoch85** [comment]
Well, I'm not convinced, but OK. We can always revert.

**Pull request merged**
