### PR TITLE
ask_yes_or_no questions not working

### PR DESCRIPTION
**Pull request by ggeorgg**
I just wanted to test the script to select the disk and I tried it using
`curl -sSL https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh | sudo bash`
but unfortunately I was not questioned the yes_or_no questions... I think the proposed change will avoid this problem but I have not tested it directly like this.
Do you also see this problem? Or is it only me?

### CODE REVIEW

**Comment by enoch85** [comment]
Please test if it works. I'm busy with some Wordpress development right now. 

Thank you very much!

**Comment by ggeorgg** [comment]
Here the reason why the old method is not working for me: [stackechange](https://unix.stackexchange.com/questions/180383/piping-a-script-with-read-to-bash)
And this is how It looks like on my virtualbox when testing:
virtualbox_ubuntu server_09_12_2018_10_03_02
(The content of the test file on the right hand side. Commands on the left window pane)

**Comment by enoch85** [comment]
Use plain wget instead works. Any specific reason you would want `curl`?

**Comment by ggeorgg** [comment]
No specific reason for curl on my side. I just stayed with as it has already been used before.
I tested the latest commit and can confirm that the yes_or_no questions work like this.

**Pull request merged**
