### PR TITLE
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by enoch85**
Signed-off-by: enoch85 <github@hanssonit.se>

Here we will develop the new VM for Ubuntu 22.04, expected release when Ubuntu 22.04.1 are live

### CODE REVIEW

**Comment by enoch85** [comment]
OK, testing stops here, turns out not even NC 24 supports PostgreSQL 14.

**Comment by enoch85** [comment]
Tested and works in current state!

To test:
1. Install Ubuntu 22.04 server: 2 disks + OpenSSH-server.
2. `wget https://raw.githubusercontent.com/nextcloud/vm/UBUNTU-22.04/nextcloud_install_production.sh`
3. `sudo bash nextcloud_install_production.sh`
4. Enjoy!

**Comment by enoch85** [comment]
TODO: 

1. Check password check for ncadmin, doesn't seem to work. Installs OK though.

**Comment by szaimen** [comment]
I will try to test through a few of the scripts going forward, especially the ones in the not-supported folder.

---

> To test:
> 
> 1. Install Ubuntu 22.04 server: 2 disks + OpenSSH-server.
> 2. `wget https://raw.githubusercontent.com/nextcloud/vm/UBUNTU-22.04/nextcloud_install_production.sh`
> 3. `sudo bash nextcloud_install_production.sh`
> 4. Enjoy!

Which of both did you choose when installing jammy?
image

**Comment by enoch85** [comment]
I chose the full installation, but will go with minimal later on.

So please test everything on minimal. 👍🏻

**Comment by enoch85** [comment]
It installs OK on minimal as well. 

One thing we should check is if we really need to build `smbclient `with `pecl` or not. I think the version in Ubuntu 22.04 would be enough.

**Comment by enoch85** [comment]
Needs more testing, but the changes from today works as intended anyway. :+1:

**Comment by szaimen** [comment]
> Needs more testing, but the changes from today works as intended anyway. 👍

Due to a plan change I will earliest be able to do my test the coming weekend. Hope that is fine...

**Comment by enoch85** [comment]
> > Needs more testing, but the changes from today works as intended anyway. +1
> 
> Due to a plan change I will earliest be able to do my test the coming weekend. Hope that is fine...

Sure, no problem. I don't plan to release this soon anyway. The Nextcloud 23.0.2 is steady as is, and users will be upgraded to latest 23 anyway. I will wait for 24.0.1 before I make a new release of the VM. Too many issues in the last releases...

**Comment by szaimen** [comment]
> Sure, no problem. I don't plan to release this soon anyway. The Nextcloud 23.0.2 is steady as is, and users will be upgraded to latest 23 anyway. I will wait for 24.0.1 before I make a new release of the VM. Too many issues in the last releases...

Okay cool!

**Comment by enoch85** [comment]
@szaimen TIme to remevoe all legacy stuff. Please check for TODO.

**Comment by enoch85** [comment]
@szaimen I'm pretty confident with merging this when NC 24.0.0 is out, then release the VM with 24.0.1.

Please test what you need this weekend so that we can merge soon.

Thanks!

**Comment by szaimen** [comment]
> Please test what you need this weekend so that we can merge soon.

I'll try!

**Comment by szaimen** [comment]
Would be cool if you could wait before I am done testing because there is a lot to test from my side...

**Comment by enoch85** [comment]
@szaimen Like stated, when 24.0.0 is out, I plan to merge this. We could always do follow up PRs if needed of course.

**Comment by szaimen** [comment]
> @szaimen Like stated, when 24.0.0 is out, I plan to merge this. We could always do follow up PRs if needed of course.

Yes but since my guide https://szaimen.github.io/Nextcloud-NAS-Guide/ relies on master I'd rather test as much as possible before merging this...

**Comment by szaimen** [comment]
> Well, then it should be on your top priority. :D

yes, it is but I could due to other circumstances not test it earlier than this weekend. One of the reasons is that I am currently covid-19-positive.

**Comment by chrisbley** [comment]
TLS activation seems to break my apache, this is the end of my apache2 error log:
https://www.toptal.com/developers/hastebin/ufafivaxaw.yaml

Tried this both as an all-at-once-setup and @szaimen 's way deselecting all options at first run, finishing the setup script and later manually running the different install and setup scripts.

Any advice?

**Comment by enoch85** [comment]
Note to self:

echo "deb https://repo.delellis.com.ar focal focal" > /etc/apt/sources.list.d/20-pdlib.list
wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
apt update
apt install php7.4-pdlib

**Comment by enoch85** [comment]
@chrisbley Could you please debug as follows:

1. https://community.letsencrypt.org/t/all-fine-but-apache-error-log-certificate-does-not-include-an-id-which-matches-server-name/14695/5
2. `cat /var/log/apache2/error.log`

**Comment by enoch85** [comment]
@szaimen Just tested and everything installs perfectly fine.

I will merge this tonight if you don't have any objections? When in master it's also easier to add more PRs to fix "side effect bugs".

**Comment by szaimen** [comment]
Unfortinately I didn't get to testing yet because covid didn't want to vanish. If you want to merge this fast I guess I need to add a warning in my guide then until I am done testing...

**Comment by enoch85** [comment]
@szaimen Sorry to hear that. :/

I added back a few of the legacy variables, so you should be fine.

**Comment by enoch85** [comment]
I'm fine with the failing tests. Will have a look later.

**Comment by szaimen** [comment]
> I added back a few of the legacy variables, so you should be fine.

thanks!

**Pull request merged**
