### PR TITLE
let the user choose username

### PR DESCRIPTION
**Pull request by enoch85**
Fixes https://github.com/nextcloud/vm/issues/488

### CODE REVIEW

**Comment by enoch85** [comment]
@ggeorgg I think `$ICyan` looks better than `$Cyan`. Would you mind creating a PR that changes to `$ICyan` everyehere?

**Comment by ggeorgg** [comment]
See #746

**Comment by ggeorgg** [comment]
By the way: I like this commit here ;)

**Comment by enoch85** [comment]
Yeah, easy fix, just didn't do it until now. :)

**Pull request merged**
