### PR TITLE
change check for sudo user

### PR DESCRIPTION
**Pull request by enoch85**
needs testing, especially with a pure root account

### CODE REVIEW

**Comment by Ark74** [comment]
Testing...
sudo_root

**Comment by Ark74** [comment]
If this pure root was in order to fix FTS issue with password change, then it didn't work.
1. Clean install
2. Enable root password  (sudo passwd root)
3. Login with root
4. Run sudo_user branch
fts1-4

**Comment by enoch85** [comment]
You shoudn't run the script with a pure root user. That's not by design and you will get warned if you do so.

I'm testing the master branch now to see if the fixes I made earlier made any difference.

Worst case, move the password stuff before installing of apps.

**Comment by Ark74** [comment]
Oh man, then did I misunderstood this?

> needs testing, especially with a pure root account

I thought that was the purpose of this test.
I'll leave it at that.

**Comment by Ark74** [comment]
I'll second this;

> Worst case, move the password stuff before installing of apps.

**Comment by enoch85** [comment]
> Oh man, then did I misunderstood this?

I was thinking if you are running from DO, you are prompted to change user, but in case you don't this should work anyway. 

BTW, this has nothing to do with FTS failing afaik.

Btw, join me on Talk: https://cloud.techandme.se/call/db33x6wj

**Pull request closed without merging**
