### PR TITLE
Ask for keyboard layout change

### LINKED ISSUE #140: Ask users to change variables
I think that for the sake of automation/ease and user preference we should ask if the user wants/requires to change variables such as:
* Static IP / Over DHCP
* [System user password](https://github.com/nextcloud/vm/blob/Ark74-ask-kblo/nextcloud-startup-script.sh#L667)
* [NC user password](https://github.com/nextcloud/vm/blob/Ark74-ask-kblo/nextcloud-startup-script.sh#L683)
* Also keyboard layout changes #139 

I've proposed that every question only waits for certain time, if no interaction then the default value will be applied.
Which in most of the cases is a denial of the change.

### PR DESCRIPTION
**Pull request by Ark74**
Instead of forcing the keyboard change, ask user or skip it if not answer given.

Fixes #140

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks for your PR @Ark74 

Please be consistent and use the same Yes/No function as here: https://github.com/nextcloud/vm/blob/407c5d7de95fa1bbf26e4a9ca0e7ee9df05b6d8d/nextcloud-startup-script.sh#L429-L437 his one catches all the digits, instead of just N or Y

**Comment by Ark74** [comment]
Sure, i'm on it.

**Comment by enoch85** [comment]
You still haven't added the function I was talking about...

**Comment by enoch85** [comment]
Oh just saw it... The reason why the user have to hit any key, is to read the instructions about opening ports before. Please revert. Sorry, I should have checked before. Kind of tired now.

And still no function as described [here](https://github.com/nextcloud/vm/pull/139#issuecomment-281941994)

**Comment by Ark74** [comment]
It is on both of the keyboard layout reconfiguration.
Install and startup scrip.

**Comment by enoch85** [comment]
Tired now, but that's what I meant all along... you missed the function part. ---^

**Comment by Ark74** [comment]
I'll study that part. Thanks.
Read you in the morning.

**Pull request merged**
