### PR TITLE
Always keep local configuration when updating

### PR DESCRIPTION
**Pull request by enoch85**
Please review @nextcloud/vm

### CODE REVIEW

**Comment by enoch85** [comment]
Maybe a better option is to re-add all the custom configs in php.ini (this is the fix for that) if they don't exist after upgrade instead of forcing something by default?

Changes are made to max upload + redis.so and smbclient.so as extentions in php.ini...

**Comment by Ark74** [comment]
That would be a wider approach. :)
BTW, i thought you refer to the nextcloud config.php not the php config.

**Comment by enoch85** [comment]
> That would be a wider approach. :)

What would be?

**Comment by Ark74** [comment]
Look up for strings like 
- redis.so
- smbclient.so
- upload_max_filesize = 1000M
- memory_limit = 512M

At php.ini right after `apt dist-upgrade` so if they are not, they get re-added, if they are, nothing else happen so that way wherever the user choose nextcloud would not be compromised.
Since the system is a nextcloud vm/box.

**Comment by enoch85** [comment]
Ok, so you think that approach is better?

**Comment by enoch85** [comment]
Let's merge this for now, and write a better solution later on.

**Pull request merged**
