### PR TITLE
Optionally change mirrors

### PR DESCRIPTION
**Pull request by Ark74**
Enable the option to choose mirrors or don't.

### CODE REVIEW

**Comment by Ark74** [comment]
Some VPS providers have faster mirrors that are not publicly available.
So in some cases it would be better to leave them as they are. 

What's your opinion on it?

**Comment by enoch85** [comment]
Thanks for your PR @Ark74! :)

I've also thought about this, but decided not to implement it because it's confusing. Let's say that your totally new to UNIX and you get a question like this. I would always answer "yes I want to keep local mirrors" and then never get the best mirror.

I also noticed that the local mirrors are picked up by apt-select. Digitalocean for instance.

@nextcloud/vm What do you think?

**Comment by enoch85** [comment]
Also, you could get presented with the 3 best mirrors and decide which one you want, or if you want to discard them I think that would actually be a better solution if we should go this path.

**Comment by Ark74** [comment]
> you could get presented with the 3 best mirrors and decide which one you want
It would be equal to always change default mirrors, right?

**Comment by enoch85** [comment]
>What about setting a timer with a pre-configured option for newbies?
Read has -t option to set time for an answer.

Experiment with it and see what you can come up with. :)

> It would be equal to always change default mirrors, right?

Yes, but we could put everything after `else` and make everything optional.

**Comment by Ark74** [comment]
The latest commit, show the default host mirror. That should give a better idea, right?

**Pull request merged**
