### PR TITLE
Adjust file ownership and permissions

### PR DESCRIPTION
**Pull request by admarty**
Adjust file ownership and permissions before reboot

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks for your PR, but why do you need this?

We already have a script that sets permissions for everything.

**Comment by admarty** [comment]
I just spin up a VM Ubuntu-22-LTS to install using the above script and here is the result:

image

**Comment by enoch85** [comment]
Yes, those are the expected permissions.

**Comment by enoch85** [comment]
Here's the script in question: https://github.com/nextcloud/vm/blob/master/static/setup_secure_permissions_nextcloud.sh

**Pull request closed without merging**
