### PR TITLE
fix the update to NC20 issue

### PR DESCRIPTION
**Pull request by szaimen**
fix https://github.com/nextcloud/vm/issues/1513

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]
For NC20 minimum php version is 7.2
For NC21 it will be 7.3

**Comment by enoch85** [comment]
Looks good @rakekniven?

**Comment by rakekniven** [comment]
Dialogs are still the same.
Do I need to do something else other than running '/var/scripts/update.sh' again to get the change?

**Comment by enoch85** [comment]
> Do I need to do something else other than running '/var/scripts/update.sh' again to get the change?

Nope, once this is merged, wait 10 minutes for Github cache and then it should work automatically. :+1:

**Pull request merged**
