### PR TITLE
New branch for another approach for collabora script

### PR DESCRIPTION
**Pull request by Ark74**
The script is almost complete, it has some issues when checking for the DNS resolution (commented out).
I'll keep testing, comments are welcome.

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks for the PR, but please use the new version I pushed to master just an hour ago. Made some changes there and added some checks. Will have a look at this tomorrow.

**Comment by enoch85** [comment]
*Copied from https://github.com/nextcloud/vm/pull/79*
@Ark74 

Please remember, this VM is not for users like us, it's for users with NO knowledge in Linux, SSL, HTTP, HTTPS, Dockers, VMs or whatever.
That's right, we should also take into account that ssl certs bring some administration responsibility.
I'm thinking about splitting into

Standard mode
Advance mode
So the standard one uses Let's Encrypt and the advance could use the users certs by copying-pasting the content of the crt/key/pem files.

Do you want to be added as a maintainer?
I sure would like, but let me figure github a little more, i would not like to mess something up by ignorance.

**Comment by enoch85** [comment]
@Ark74 Please use the latest master to fix the issues with the conflicts. Thanks!

**Comment by enoch85** [comment]
@Ark74 I've fixed Collabora now so that it's stable. Will add even more checks to make it more user friendly. 

Sorry, but I don't see the purpose any longer for this PR. Feel free to continue or to close.

Thanks!

**Comment by Ark74** [comment]
Your are right. And to be honest i haven't had the time to really work on it.
Let's continue from that one.

**Pull request closed without merging**
