### PR TITLE
Can elasticsearch container be bound only to localhost?

### PR DESCRIPTION
**Pull request by hatclub**
Is there any reason this container should expose ports to external network by default? 

I have seen that it's got the readonlyrest authenticating layer on it so I know it's not just "wide open", but it seems unnecessary from a security standpoint for it to be listening on 0.0.0.0 by default in this context?

### CODE REVIEW

**Comment by enoch85** [comment]
I'll need to consult @Ark74 on this.

**Comment by Ark74** [comment]
Hi!
No not really, at some point it is useful for some minor admin task on elasticsearch I guess you could always do those running within the VM.
As you mention it, there is an authorization mechanism so, it's not open as such.

A PR on this regard is welcome.

**Comment by Ark74** [comment]
@enoch85 if you don't have any issue.
@hatclub can fix his commit and we can merge it.

**Comment by hatclub** [comment]
> @hatclub can fix his commit and we can merge it.

Sorry, what do you need from me here?

**Comment by enoch85** [comment]
Fixed :)

So you'd say it's OK to merge @Ark74?

**Comment by enoch85** [comment]
Just saw your approval... (I'm also blind)

**Pull request merged**
