### PR TITLE
Update format-chosen.sh

### PR DESCRIPTION
**Pull request by omnidelic**
Add Intel NUC to SYSVENDOR test to correctly identify 2nd disk during install.

### CODE REVIEW

**Comment by omnidelic** [comment]
Not sure if SYSNAME should be assigned to "machines" instead?

**Comment by Haxy89** [comment]
I think static/format-sdb.sh should be updated too

**Comment by omnidelic** [comment]
You're right, I'll add that to the PR :)

**Comment by enoch85** [comment]
OK, code wise it looks good. Im not sure that all "Intel Client Systems" are Intel NUCs, but let's merge and see if we get any bug report about it in the future. Probably not. :)

**Pull request merged**
