### PR TITLE
Shell scripts minor fixes

### PR DESCRIPTION
**Pull request by vazhnov**
* extra spaces removed
* `SPDX-License-Identifier: GPL-3.0-only` added

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks! <3

Please change the license text to:
# T&M Hansson IT AB © - 2021, https://www.hanssonit.se/
# GNU General Public License v3.0
# https://github.com/nextcloud/vm/blob/master/LICENSE

Please add the above text in all files. :+1:

**Comment by vazhnov** [comment]
@enoch85 , please check

**Comment by enoch85** [comment]
@vazhnov Great, thanks!

Could you please add the same license text in all files in this repo?

**Comment by vazhnov** [comment]
@enoch85 , let's keep this change (license text in all files) for a separate merge request.

**Pull request merged**
