### PR TITLE
minor corrections

### PR DESCRIPTION
**Pull request by enoch85**
1. remove trusted proxies if 127.0.0.1
2. reload daemon
3. add sleep

cc @szaimen

### CODE REVIEW

**Comment by enoch85** [comment]
The reason for `systemctl daemon-reload`

```
root@nextcloud:~# bash /var/scripts/menu.sh 
Updating lib...
Running the main menu script...
Testing if network is OK...
Waiting for network to restart...
Checking connection...
Updating lib...
Downloading the Additional Apps Menu...
Updating lib...
Downloading the Notify Push script...
Updating lib...
Checking if Nextcloud is installed...
Reinstalling Push Notifications for Nextcloud...
notify_push disabled
notify_push 0.1.4 removed
Reinstalling Push Notifications for Nextcloud...
Installing notify_push...
notify_push 0.1.4 enabled
notify_push 0.1.4 disabled
                    Warning: The unit file, source configuration file or drop-ins of notify_push.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Module proxy already enabled
Considering dependency proxy for proxy_http:
Module proxy already enabled
Module proxy_http already enabled
Considering dependency proxy for proxy_wstunnel:
Module proxy already enabled
Module proxy_wstunnel already enabled
It seems like notify_push is installed already, trying to enable it...
notify_push 0.1.4 enabled
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
✓ push server is running the same version as the app
  configuration saved
root@nextcloud:~# 
```

**Comment by enoch85** [comment]
Fix https://github.com/nextcloud/vm/issues/1853

**Comment by enoch85** [comment]
Current test:

```
🗴 can't connect to push server: Server error: `GET https://nextcloud.xxxx.xxx/push/test/cookie` resulted in a `503 Service Unavailable` response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1 (truncated...)
```

**Comment by szaimen** [comment]
@enoch85 is this PR ready?

**Comment by enoch85** [comment]
@szaimen I was stressed when I did it, and since you are the author of the original script, I thought you should have a look before we merge. 

Please test this properly.

**Comment by szaimen** [comment]
@enoch85 with my small fix, it works for me every time.

**Comment by enoch85** [comment]
OK, let's merge this and I'll keep my eyes open for that error in the future. It complained that systemctl needed to be reloaded and my guess it's happening when you first remove the service, without reloading, and then adds it back.

But let's see...

**Comment by szaimen** [comment]
It just complained because the service was still enabled. Since it gets disabled by my small fix it doesn't complain anymore.

**Comment by enoch85** [comment]
Just tested, works like a charm! <3

**Pull request merged**
