### PR TITLE
allow to reinstall automatic updates

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 What about beeing able to reinstall automatic updates? (hence beeing able to disable it?)

**Comment by enoch85** [comment]
> @enoch85 What about beeing able to reinstall automatic updates? (hence beeing able to disable it?)

Sure, why not. 

I also just added a new issue regarding the updates here: https://github.com/nextcloud/vm/issues/1680

I would like to refactor this in general actually.

**Comment by enoch85** [comment]
But, I don't get this fix? This wouldn't write anything to the log, right?

**Comment by szaimen** [comment]
> But, I don't get this fix? This wouldn't write anything to the log, right?

No, this will write also error messages to the logfile which it doesn't do currently.

**Comment by szaimen** [comment]
this will be implemented with #1681

**Pull request closed without merging**
