### PR TITLE
possible fix for missing second disk import (zfs)

### PR DESCRIPTION
**Pull request by enoch85**
zpool.cache have a tendency to fail. This PR aims to make it more robust so that users don't manually have to import the zpool with `zpool import` just to get up and running in case the pool failed to import during boot.

New script https://github.com/nextcloud/vm/blob/master/static/change-to-zfs-mount-generator.sh

### CODE REVIEW

**Comment by enoch85** [comment]
@zalonic What's your view on this? (Since you helped out with the format-sdb script)

**Comment by enoch85** [comment]
This is confirmed to have fixed it for at least two people with a broken system.

I will merge this to be released in Nextcloud 18.0.5/19.0.0 (whichever comes first).

It would still be nice with some input though @zalonic @penzoiders

**Comment by penzoiders** [comment]
Unfortunately this fix is needed on ubuntu, on other systems (.rpm based) I never had such an issue. Your workaround looks fine. Although I can't test it in production since I don't use ZFS on my VMs (It's already underneath the storage layer, don't have much sense to have 2 slices of zfs for me).

**Comment by enoch85** [comment]
Yeah, it's an Ubuntu bug. :(

Thanks for your input! :rocket:

**Comment by zalonic** [comment]
Afternoon, sorry for not coming back to you sooner. I've checked the workaround and it seems okay so we've swapped out our Development Team NAS in production with the updated ZFS one referenced here. We are replicating the data back to the old stable one just in case as a backup and let you know on Friday if any issue crop up with the new configuration, as far as I can see so far, can't see any issues popping up.

**Comment by enoch85** [comment]
Thanks @zalonic! Really appreciated!

**Comment by zalonic** [comment]
Hi @enoch85, day 4 of running the updated NcVM, happy to say everything is operating as expected.

**Comment by enoch85** [comment]
Thanks for the feedback! :D

**Pull request merged**
