### PR TITLE
chown .bash_profile to correct user as it's created by root

### LINKED ISSUE #44: contacts not downloadable
## Steps to reproduce
1. started script  nextcloud_install_production.sh
2. new script with install contact only

[install_contacts.sh.txt](https://github.com/nextcloud/vm/files/522768/install_contacts.sh.txt)

## Expected behaviour
first part of an new install should happen.
## Actual behaviour
version 1.5.0.0 could not be downloaded 
## Server configuration

**Server version:** (see your admin page)
nextcloud 10.0.1
**VM version**
ubuntu server 16.4.1

**fresh install:**
only first Part until first reboot.

#### Web server error log
```
Insert your install contacts log here

kk@nctest3:~$ sudo bash install_contacts.sh 2>&1 | tee contacts.log
[sudo] Passwort für kk: 
+ WWW_ROOT=/var/www
+ NCPATH=/var/www/nextcloud
++ wget -q https://raw.githubusercontent.com/owncloud/contacts/master/appinfo/info.xml
++ grep -Po '(?<=<version>)[^<]*(?=</version>)' info.xml
++ rm info.xml
+ CONVER=1.5.0.0
+ echo 'ContactVersion = 1.5.0.0'
ContactVersion = 1.5.0.0
+ CONVER_FILE=contacts.tar.gz
+ CONVER_REPO=https://github.com/owncloud/contacts/releases/download
+ '[' -d /var/www/nextcloud/apps/contacts ']'
+ wget -q https://github.com/owncloud/contacts/releases/download/v1.5.0.0/contacts.tar.gz -P /var/www/nextcloud/apps
+ tar -zxf /var/www/nextcloud/apps/contacts.tar.gz -C /var/www/nextcloud/apps
tar (child): /var/www/nextcloud/apps/contacts.tar.gz: Funktion open fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ cd /var/www/nextcloud/apps
+ rm contacts.tar.gz
rm: das Entfernen von 'contacts.tar.gz' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
+ '[' -d /var/www/nextcloud/apps/contacts ']'

### PR DESCRIPTION
**Pull request by enoch85**
Fixes #44

Please test @eplusk

### CODE REVIEW

**Comment by enoch85** [comment]
Note to self; make same change on ownCloud VM as well.

**Comment by enoch85** [comment]
@eplusk can I get a :+1: from you?

**Comment by eplusk** [comment]
Now it's OK

Klaus

**Comment by enoch85** [comment]
@eplusk I need your :+1: (+1:)

**Comment by enoch85** [comment]
Or nvm I can merge anyway :)

**Comment by eplusk** [comment]
@enoch85 
Please be patient with me, I have no problems with bash-scripting, but I'm new to GIT. And I have to learn the procedures of git. 
Greetings Klaus

**Comment by enoch85** [comment]
@eplusk No worries, I really appreciate your work, testing our scripts! Thank you! You're welcome to join #techandme on IRC if you want to chat. :) If you don't have a client you can join here: https://webchat.freenode.net/?channels=techandme

**Pull request merged**
