### PR TITLE
Don't execute the update before all cronjobs are finished

### PR DESCRIPTION
**Pull request by szaimen**
Prevents issues like https://github.com/nextcloud/spreed/issues/5518
Is discussed in https://github.com/nextcloud/server/issues/28508
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
This is ready 👍

**Comment by enoch85** [comment]
We do `occ upgrade` in the apps section as well, so please put it there.

Thanks!

**Comment by szaimen** [comment]
Should be done 👍

**Comment by enoch85** [comment]
Superb! :100:

**Pull request merged**
