### PR TITLE
contacts are now moved to Nextcloud

### LINKED ISSUE #48: Script to install contacts has to be modified
Contacts has moved to nextcloud
Contacts doesn't have any releases any more, so the package can't be fetched.

### PR DESCRIPTION
**Pull request by enoch85**
Still wrong version number though as 1.5.0.0 is not released yet. 

Fixes #48

@oparoz for review. Thanks!

### CODE REVIEW

**Comment by oparoz** [comment]
This is not enough (yet) because the releases have not been migrated. Packages created by tags do not contain a valid signature.

**Comment by enoch85** [comment]
Ok, when will the releases be migrated?

**Comment by enoch85** [comment]
> Ok, when will the releases be migrated?

cc @irgendwie

**Comment by enoch85** [comment]
The version is fixed

**Pull request merged**
