### PR TITLE
smbmount - make backup option more understandable

### LINKED ISSUE #1967: Product's (GEN 2) built-in SMB function fails in NextCloud (Windows 10 Host)
## Steps to reproduce
1. Creation of 1 SMB mount using the Product's built-in SMB function. (Using the latest HanssonIT Hyper-V GEN 2 Product on a Windows 10 Host ). From the products SMB utility the mount is created without issue.

2. I have run the product (Fresh Start) no less then 10 times (do to other issues). Each time I cannot create the mounts in the new Nextcloud instance. 

## Expected behavior
1) Should be able to easily create the shares In NextCloud using the "External Storage" module using Local.  

## Actual behavior
1) You cannot create the shares in NextCloud using Local. 

2) It may also be causing strange UI problems. Getting "This Operation is forbidden" when moving from function to function in NextCloud. Also getting  CSRF Errors when logging out. 

## Observation
1) If I don't use the products SMB functions to create the mounts, I don't get the strange UI issues.
2) If I don't use the products SMB functions to create the mounts, I am able to create shares successfully using the External Storage modules SMB function. 
3) The SMB mount string that is created is much different from a working GEN 1 product.  

Not Working String
Not Working SMB New Script

Working String
Working SMB

## Server configuration

**Nextcloud server version:** (see your admin page)
21.0.1

**Server OS** (Ubuntu server is default)
Windows 10

**PHP Version** (e.g. 7.4)
Version: 7.4.3
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 1000 MB

**How did you install the VM?** (Scripted install from master **OR** Released version)
No Ideal, it's HanssonIT Latest Product (Purchased 2 days ago)

## Network
**Do you use DHCP?**
Fixed

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
Have no idea how to get them.

Insert your nextcloud.log file here
Have no idea how to get them.

#### Installation log (command output)
Have no idea how to get them.

Insert the CLI output here
Have no idea how to get them.

### PR DESCRIPTION
**Pull request by szaimen**
Fix #1967
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
Even better would be to make it a whiptail with two options:

- Use for backups
- Use for Nextcloud External Storage (default)

**Comment by enoch85** [comment]
It can't be more obvious than that :D

**Comment by enoch85** [comment]
ping @szaimen What do you think?

**Comment by szaimen** [comment]
I am fine with this now 👍

**Pull request merged**
