### PR TITLE
make it possible to install fts multiple times

### PR DESCRIPTION
**Pull request by enoch85**
cc @Ark74

### CODE REVIEW

**Comment by enoch85** [comment]
Tested and works!

**Comment by enoch85** [comment]
No, just in case you need to reinstall for some reason. like I did now for example, found that you can't run the apps on old indexes, it will fail, so DB tables needs to be dropped.

**Comment by enoch85** [comment]
> Oh, there is fulltextsearch:reset

Lol, just spent like 2 hours on this. 

Oh well, I learned how to use `psql` at least. :D

**Comment by Ark74** [comment]
\o/!

El 28 de septiembre de 2018 6:27:17 PM CDT, Daniel Hansson <notifications@github.com> escribió:
>> Oh, there is fulltextsearch:reset
>
>Lol, just spent like 2 hours on this. 
>
>Oh well, I learned how to use `psql` at least. :D
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/vm/pull/671#issuecomment-425593055

-- 
Enviado desde dispositivo móvil. Por favor, disculpa mi brevedad.

**Comment by enoch85** [comment]
I tested to run it both before and after. It didn't work. Where should the reset command be added to work?

**Comment by enoch85** [comment]
@Ark74 If you can make use of `fulltextsearch:reset` then we'll use that, but this works every time. Tested.

**Pull request merged**
