### PR TITLE
add PHP_MODS_DIR

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by BigDogJonx** [comment]
Hey, just tested this and  I think we need one more piece.  I reformatted my MicroSD to test the latest RPi branch and this smbclient issue and it still didnt work.  Looked at it and the smbclient.ini edit is there which is good.  But still didnt index the files.  

Once I ran the cmd of `sudo phpenmod -v ALL smbclient` I got it to work.

Before I ran it, I didnt put sudo, and it gave me the following issues, so I think we need to add that to the script as well to make it work (get it enabled).
```
ncadmin@rpi:~$ phpenmod -v ALL smbclient
ln: failed to create symbolic link '/etc/php/7.4/cli/conf.d/20-smbclient.ini': Permission denied
touch: cannot touch '/var/lib/php/modules/7.4/cli/enabled_by_admin/smbclient': Permission denied
```

**Comment by enoch85** [comment]
Aah, right!

I was feeling that there were something missing before I merged. :) 

Will sort that soon.

**Comment by enoch85** [comment]
@BigDogJonx Please try master again.

Thanks!

**Comment by BigDogJonx** [comment]
> @BigDogJonx Please try master again.
> 
> Thanks!

@enoch85 Sorry was out of town and away from my comps to play with them physically, just got back and tested this and worked out the box on a full install from the master scripts.  So this is good to go for sure, we can push this to the RPi branch too.  Thanks

Dixit

**Comment by enoch85** [comment]
Everything on master as of today is now merged into rpi.

**Comment by BigDogJonx** [comment]
@enoch85 Awesome.  I tested the script a few days ago again from a clean Ubuntu image on my RPi and worked good (just had to manually enable the phpenmod for smbclient, so with this now merged that should be good.  I technically put mine in "production" (the RPi) and turned off the VM Nextcloud to now put it a bit more to the test.  So far been hitting it with things and working fine.  I can see this remaining as my permanent solution.

**Pull request merged**
