### PR TITLE
create is_app_installed

### PR DESCRIPTION
**Pull request by szaimen**
those are the places where to implement it: 
vm/apps/fulltextsearch.sh:if [ -d $NC_APPS_PATH/fulltextsearch ]
vm/apps/fulltextsearch.sh:if [ -d $NC_APPS_PATH/fulltextsearch_elasticsearch ]
vm/apps/fulltextsearch.sh:if [ -d $NC_APPS_PATH/files_fulltextsearch ]
vm/apps/previewgenerator.sh:    if [ -d "$NC_APPS_PATH/previewgenerator" ]
vm/lib.sh:if [ ! -d "$NC_APPS_PATH/$1" ]
vm/lib.sh:        if [ -d "$NC_APPS_PATH/$1" ]

But for fulltextsearch, I will wait until https://github.com/nextcloud/vm/pull/1093 is merged.

### CODE REVIEW

**Comment by enoch85** [comment]
@szaimen FTS is merged. :D

**Comment by szaimen** [comment]
I think this is ready for review. The function was already tested by me before.

**Comment by enoch85** [comment]
Looks good to me!

**Comment by enoch85** [comment]
I think you missed a few places though:

```
apps/onlyoffice.sh:    chown -R www-data:www-data "$NC_APPS_PATH"
apps/spreedme.sh:if [ -d "$NC_APPS_PATH/spreedme" ]
apps/spreedme.sh:    rm -R "$NC_APPS_PATH/spreedme"
apps/spreedme.sh:chown -R www-data:www-data "$NC_APPS_PATH"
apps/talk.sh:if [ ! -d "$NC_APPS_PATH"/spreed ]
apps/talk.sh:    chown -R www-data:www-data "$NC_APPS_PATH"
apps/talk.sh:if [ -d "$NC_APPS_PATH"/spreed ]
apps/previewgenerator.sh:    if [ -d "$NC_APPS_PATH/previewgenerator" ]
apps/collabora.sh:            if [ -d "$NC_APPS_PATH"/richdocuments ]
apps/collabora.sh:            if [ -d "$NC_APPS_PATH"/richdocuments ]
apps/collabora.sh:if [ -d "$NC_APPS_PATH"/onlyoffice ]
apps/collabora.sh:if [ -d "$NC_APPS_PATH"/richdocuments ]
apps/collabora.sh:    chown -R www-data:www-data "$NC_APPS_PATH"
apps/fulltextsearch.sh:            if [ -d $NC_APPS_PATH/fulltextsearch ]
apps/fulltextsearch.sh:                rm -rf $NC_APPS_PATH/fulltextsearch
apps/fulltextsearch.sh:            if [ -d $NC_APPS_PATH/fulltextsearch_elasticsearch ]
apps/fulltextsearch.sh:                rm -rf $NC_APPS_PATH/fulltextsearch_elasticsearch
apps/fulltextsearch.sh:            if [ -d $NC_APPS_PATH/files_fulltextsearch ]
apps/fulltextsearch.sh:                rm -rf $NC_APPS_PATH/files_fulltextsearch
apps/fulltextsearch.sh:            if [ -d $NC_APPS_PATH/fulltextsearch ]
apps/fulltextsearch.sh:                rm -rf $NC_APPS_PATH/fulltextsearch
apps/fulltextsearch.sh:            if [ -d $NC_APPS_PATH/fulltextsearch_elasticsearch ]
apps/fulltextsearch.sh:                rm -rf $NC_APPS_PATH/fulltextsearch_elasticsearch
apps/fulltextsearch.sh:            if [ -d $NC_APPS_PATH/files_fulltextsearch ]
apps/fulltextsearch.sh:                rm -rf $NC_APPS_PATH/files_fulltextsearch
apps/fulltextsearch.sh:if [ -d "$NC_APPS_PATH"/nextant ]
apps/fulltextsearch.sh:    rm -rf $NC_APPS_PATH/nextant
apps/fulltextsearch.sh:chown -R www-data:www-data $NC_APPS_PATH
lib.sh:if [ ! -d "$NC_APPS_PATH/$1" ]
lib.sh:        if [ -d "$NC_APPS_PATH/$1" ]
```

**Comment by szaimen** [comment]
So in conclusion:
1x in spreedme (but that shouldn't get changed? Since it is too old?)
2x in talk
1x in previewgenerator
4x in collabora
7x in fulltextsearch
2x in lib

**Comment by szaimen** [comment]
Based on my list:
What is missing is talk and collabora. I will fix that later on.

**Comment by szaimen** [comment]
I think I have all. 

and btw: are these type of lines really needed:
`rm -rf $NC_APPS_PATH/files_fulltextsearch`
Isn't the occ_command app:remove files_fulltextsearch working here?

**Comment by enoch85** [comment]
> Isn't the occ_command app:remove files_fulltextsearch working here?

You could test, but I think I added it just as a precaution. 

If `occ app:remove` works, then please delete it.

**Comment by szaimen** [comment]
I've just tested occ app:remove and it removes the whole folder from that specific app. So I would say it is save to use that.

**Comment by szaimen** [comment]
This should be ready now.

btw: I am pretty sure, that we don't need `chown -R www-data:www-data "$NC_APPS_PATH"` when installing apps through the nextcloud store (because else wouldn't make any sense), but the last time you didn't want me to delete it...

**Comment by enoch85** [comment]
It doesn't hurt to `chown`. Let's merge.

**Pull request merged**
