### PR TITLE
fix some issues with smtp-mail

### PR DESCRIPTION
**Pull request by szaimen**
While debugging #1563 I discovered this issue.

As I said this was my guide:
https://decatec.de/linux/linux-einfach-e-mails-versenden-mit-msmtp/
And there you can see that those values (account and account default) definitely should be the mail_username.
I've tested this successfully with my account.

### CODE REVIEW

**Comment by szaimen** [comment]
oh, wrong label. This is ready for review :)

**Comment by enoch85** [comment]
What issue does this fix? My german isn't perfect. :)

**Comment by enoch85** [comment]
With passwordless auth there is no account...

**Comment by szaimen** [comment]
I am refering ro those lines (they are english)

**Comment by enoch85** [comment]
Yes, I saw that. But what does it actually fix? Is it an issue to have the server instead?

Also: 

> With passwordless auth there is no account...

**Comment by szaimen** [comment]
> Yes, I saw that. But what does it actually fix? Is it an issue to have the server instead?

I had some issues with this while testing (it said something like account not defined or so)
And it is recommended as you can see in the screenshot.

> With passwordless auth there is no account...

Do you mean that "$MAIL_USERNAME" is empty in this case?
I don't think so:
https://github.com/nextcloud/vm/blob/1d92bb6f1b075ccb83e53961f3fe0304dbb54224/addons/smtp-mail.sh#L147-L150

**Comment by szaimen** [comment]
What about changing it to mail_username only for configurations where auth is on?
What do you think?

**Comment by enoch85** [comment]
Nvm, let's merge this.

**Comment by enoch85** [comment]
Once you start merging you can stop.

external-content duckduckgo com

**Pull request merged**
