### PR TITLE
smart-monitoring - fix initial disk check

### LINKED ISSUE #1914: S.M.A.R.T check instantly dooms VM disk as failed.
Since the last update the S.M.A.R.T  check thinks that the VM disk is bad on a new computer (my laptop) with a fresh VM.

This is wrong.

I think that the reason is that VM disks aren't supported to be run S.M.A.R.T checks on. In the previous code no real error was made clear, and it silently "failed" (aka didn't produce anything since it's badly supported running in VMs). Maybe that needs to be looked at. Right now everyone running the VM will have S.M.A.R.T  errors automatically.

@szaimen

### PR DESCRIPTION
**Pull request by szaimen**
Fix #1914
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Now I remember why I've initially tested the smart capability like this. I've tested it successfully on a VM 👍

**Comment by enoch85** [comment]
Maybe it's better to `grep` for this?

image

**Comment by enoch85** [comment]
This works btw, just tested. :+1:

**Comment by szaimen** [comment]
> Maybe it's better to `grep` for this?
> 
> image

No, unfortunately this isn't always shown if a drive lacks smart capability. E.g. I own a drive that not even prints this message out.

**Pull request merged**
