### PR TITLE
Adjust whiptail styling to fit Nextcloud a bit better

### PR DESCRIPTION
**Pull request by szaimen**
It is based on this:
https://askubuntu.com/questions/776831/whiptail-change-background-color-dynamically-from-magenta

This is how it looks like now:
image
image
image
image

### CODE REVIEW

**Comment by szaimen** [comment]
Todo: tryout
- entry=blue,brightblue
- helpline=brightblue,brightblue

**Comment by enoch85** [comment]
Sorry, I don't like this. :-1:

**Comment by szaimen** [comment]
> Sorry, I don't like this. 👎

Why? Please tell me and I'll close it.

**Comment by enoch85** [comment]
Because it's ugly. :D

**Comment by szaimen** [comment]
> Because it's ugly. :D

Okay, that is a good reason :D
Too bad, I really tried to make it pretty 😅

**Comment by enoch85** [comment]
> Too bad, I really tried to make it pretty sweat_smile

Thanks for your efforts, but to me it looks lame. Like "baby colors". 

If one could specify colors with hex code and use exactly the same as Nextcloud use, then it **might** be interesting.

**Comment by szaimen** [comment]
The problem is you are limited to those, afaik:
```
color0  or black
color1  or red
color2  or green
color3  or brown
color4  or blue
color5  or magenta
color6  or cyan
color7  or lightgray
color8  or gray
color9  or brightred
color10 or brightgreen
color11 or yellow
color12 or brightblue
color13 or brightmagenta
color14 or brightcyan
color15 or white
```

**Pull request closed without merging**
