### PR TITLE
Update all files to use local lib if existant

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 any idea why travis reports these Shellcheck issues although they should be disabled?

**Comment by enoch85** [comment]
[Here](https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L35-L62) it's only used one time.

**Comment by szaimen** [comment]
Yes, I know. But it is a backwards compatibility decision...

**Comment by enoch85** [comment]
Sorry, saw this now

**Pull request merged**
