### PR TITLE
Fix lib.sh create_certs function.

### PR DESCRIPTION
**Pull request by Ark74**
Make sure certs are in place.

### CODE REVIEW

**Comment by enoch85** [comment]
I don't understand, so the script itself needs to be in the app folder?

**Comment by enoch85** [comment]
It would be much better if the path actually was correct here, not assuming that it needs to be in `./`

**Comment by Ark74** [comment]
The lines you marked are not really the issue, we could even remove them and that will not make any difference.

The path would have to be changed on every openssl command and I would prefer to avoid passing paths to openssl in this specific operation as it is a 3 step validation.

**Comment by enoch85** [comment]
Not perfect, but OK. :)

**Pull request merged**
