### PR TITLE
Create a new postgresql branch for an alternative VM (#281)

### PR DESCRIPTION
**Pull request by enoch85**
Please review @nextcloud/vm 

This will result in an additional VM that's maintained in a separate branch.

Do not merge.

A little poll: https://twitter.com/techandme_se/status/877922608955637760

### CODE REVIEW

**Comment by enoch85** [comment]
Need to merge this to be able to test on DO.

Please comment if you see anything wrong.

**Comment by enoch85** [comment]
@brantje Just noticed, you don't support PostgreSQL. Would you mind supporting it? Check this comment regarding the API: https://github.com/nextcloud/vm/pull/277#issuecomment-310600800

**Comment by enoch85** [comment]
@brantje Ping --^

**Comment by brantje** [comment]
Ah yea, see https://github.com/nextcloud/passman/issues/274 Passman seems to work, but untested.

**Pull request merged**
