### PR TITLE
fix letsencryptrenew for all geoblock configurations

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
This was successfully tested and is ready for review 👍

**Comment by szaimen** [comment]
One change is still needed

**Comment by enoch85** [comment]
Have you tested this by setting up a VPS and installed Nextcloud from the beginning, and then tried to activate TLS as usual?

I remember that the crontab wouldn't be set if run in a function, hence it's directly in the script.

**Comment by szaimen** [comment]
I've just tested renewing and getting a certificate without allowing any country or continent and it worked. -> hence this PR isn't needed

**Comment by enoch85** [comment]
Please add notify_admin_gui on line 66 if apache doesn't start.

Otherwise looks good, but not tested.

**Comment by szaimen** [comment]
Do you mean in #1905?

**Comment by enoch85** [comment]
Yes, sorry.

**Comment by szaimen** [comment]
I think I've fixed it with https://github.com/nextcloud/vm/pull/1905/commits/3d435e4cff1c7afd97422592f6ca63379fa3eaf3

**Pull request closed without merging**
