### PR TITLE
further improvements to Talk Signaling

### PR DESCRIPTION
**Pull request by enoch85**
@morph027 @szaimen 

Still internal server error, but Nextcloud reports OK, and curl command works.

**Apache2 log**
```
[Mon Aug 24 22:57:51.555540 2020] [proxy:warn] [pid 64118:tid 140500374681344] [client 5.243.70.111:60706] AH01144: No protocol handler was valid for the URL /favicon.ico (scheme 'ws'). If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
```

Apache also needs access to the logs dir.

### CODE REVIEW

**Comment by enoch85** [comment]
Funny, adding *whatever* to the `ProxyPass` removes the Internal Server Error.

```
    ProxyPass "/whatever"  "ws://127.0.0.1:8081/"
    ProxyPassReverse "/whatever"  "ws://127.0.0.1:8081/"
```

@morph027 Why are we not using "signaling-server" as in the Janus docs?

**Comment by morph027** [comment]
The initial idea was to use a separate subdomain so no path was necessary. I'm using the sub-path as well so let's change it to this.

**Comment by enoch85** [comment]
> separate subdomain

I don't understand? We are using a separate subdomain in this setup already.

**Comment by morph027** [comment]
Yes, but as we agreed on a subdomain (apache setup is much easier), we also agreed to not use a subpath. However, doesn't matter, let's use the subdomain +  path,  like signaling.example.com/signaling-server/

I will fix the script and let you know for further testing.

**Comment by szaimen** [comment]
> subdomain + path, like signaling.example.com/signaling-server/

I don't get why we need that subpath? I mean it works already by using the main domain...
What I mean is, that https://"$SUBDOMAIN"/api/v1/welcome returns the correct code...

**Comment by morph027** [comment]
> > subdomain + path, like signaling.example.com/signaling-server/
> 
> I don't get why we need that subpath?
> I mean it works already by using the main domain...
> What I mean is, that https://"$SUBDOMAIN"/api/v1/welcome returns the correct code...

You can't route `/` of the main domain to the signaling server websocket as it requires php for NC.
Also, without a subdomain, we need to add the signaling proxy into the main apache config, which gets written in another script.

Obviously, a plain `/`` for the subdomain does not work either due to bogus apache restrictions (leading to the dso error).

**Comment by szaimen** [comment]
> You can't route `/` of the main domain to the signaling server websocket as it requires php for NC.
> Also, without a subdomain, we need to add the signaling proxy into the main apache config, which gets written in another script.
> 
> Obviously, a plain `/`` for the subdomain does not work either due to bogus apache restrictions (leading to the dso error).

Yes, I get this. What I don't get is why we are now changing this to use the nextcloud-domain although the nextcloud-signaling-server already works with the subdomain...

What I am talking about is: although apache reports internal server error, the nextcloud-signalilng-server works now with this subdomain.

**Comment by morph027** [comment]
> What I am talking about is: although apache reports internal server error, the nextcloud-signalilng-server works now with this subdomain.

Even with `/` ? So the talk app in browser works when joining a room and signal server is logging connections?

Anyway, I agree, there's no need to change the subdomain to the nextcloud domain.

**Comment by szaimen** [comment]
> > What I am talking about is: although apache reports internal server error, the nextcloud-signalilng-server works now with this subdomain.
> 
> Even with `/` ? So the talk app in browser works when joining a room and signal server is logging connections?
> 
> Anyway, I agree, there's no need to change the subdomain to the nextcloud domain.

Yes, I think so. But I actually haven't looked in the logs.
But in the admin settings of talk, it reports, that the connection works...

**Comment by enoch85** [comment]
OK, let's just keep the internal server error. We can disallow index alltogether and make it forbidden instead. At least that's cleaner.

**Comment by enoch85** [comment]
Turns out we can't disallow index on the internal server error as there's no index. 

Any suggestions?

**Comment by szaimen** [comment]
Yes, but maybe first should be comfirmed, that it really works?

**Comment by enoch85** [comment]
> Yes, but maybe first should be comfirmed, that it really works?

Please login with your admin account and join the call. I'm waiting. :)

**Comment by szaimen** [comment]
one moment please

**Comment by enoch85** [comment]
JFTR, it works. :1st_place_medal:

**Comment by szaimen** [comment]
okay nice, so it is definitely working, which the test confirmed. 🚀

**Comment by morph027** [comment]
Awesome :rocket:

**Comment by szaimen** [comment]
@morph027 do you have an idea maybe how to hide the internal server error message?

**Comment by morph027** [comment]
server logs of the test vps shows in the logs:

```
Aug 24 21:28:22 ... signaling[55260]: 2020/08/24 21:28:22.910213 mcu_janus.go:303: WARNING: Full-Trickle is NOT enabled in Janus!
```

Will doublecheck the config

**Comment by enoch85** [comment]
> do you have an idea maybe how to hide the internal server error message?

I have tried:

- Custom error page - Didn't work since there's an internal server error from the beginning
- Disallow Indexes - There's no index, so nothing to disallow.

**Comment by szaimen** [comment]
I think I found a solution

**Comment by szaimen** [comment]
I've changed:
```
    ProxyPass "/"  "ws://127.0.0.1:8081/"
    ProxyPassReverse "/"  "ws://127.0.0.1:8081/"
```

to the follwing:
```
    ProxyPass "/"  "http://127.0.0.1:8081/"
    ProxyPassReverse "/"  "http://127.0.0.1:8081/"
```

Now the internal server error is gone
and a custom index.html file should theoratically work

**Comment by enoch85** [comment]
@szaimen Please join a new call for testing.

**Comment by enoch85** [comment]
Nope, doesn't work.

**Comment by szaimen** [comment]
> Nope, doesn't work.

Hm :/ maybe we should reload all services?
The admin panel still says that the connection works...

**Comment by enoch85** [comment]
Thing is, it needs to proxy **w**eb**s**ocket, not http.

**Comment by szaimen** [comment]
> Thing is, it needs to proxy websocket, not http.

Then this is of course the problem why we cannot show a html page if we just rewrite to websocket which is not http...

**Comment by enoch85** [comment]
https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

> Proxying both HTTP and websockets at the same time, with a specific set of URL's being websocket-only, can be done by specifying the websockets ProxyPass directive before the HTTP directive:

> ProxyPassMatch ^/(myApp/ws)$  ws://example.com:9080/$1
> ProxyPass / http://example.com:9080/

So, it would be possible to proxy http and ws at the same time. Question is, what are the paths to the `ws`? @morph027

**Comment by enoch85** [comment]
@szaimen I think I solved it. 

Please join another call.

**Comment by morph027** [comment]
> So, it would be possible to proxy http and ws at the same time. Question is, what are the paths to the `ws`?

The signaling server only does websockets, so the apache ws proxy needs to point to `ws://127.0.0.1:8081/`

**Comment by enoch85** [comment]
@morph027 We just tested and it works.

@szaimen One last call to confirm the fix works. Thanks!

**Comment by enoch85** [comment]
Talk test call is here: https://cloud.lindnercloud.com/call/j65ht5wt I'm waiting.

**Comment by enoch85** [comment]
Credits to https://www.itsfullofstars.de/2017/03/custom-503-error-page-for-apache/ for the error document handling.

**Comment by enoch85** [comment]
@morph027 

> The signaling server only does websockets, so the apache ws proxy needs to point to ws://127.0.0.1:8081/

The thing is that this config proxies all `ws` on `127.0.0.1:8081` and at the same time allows `http`.

Where are the logs for everything so that I can check if it actually works or not?

**Comment by enoch85** [comment]
New link: https://cloud.lindnercloud.com/call/6qpcwsw9

This is just reinstalled with this PR script.

@morph027 @szaimen Please join.

**Comment by morph027** [comment]
> Where are the logs for everything so that I can check if it actually works or not?

Signaling server logs can be viewed using `journalctl -lfu signaling` When everything works, there are a lot of lines showing established sessions, creating rooms and so on.

If it won't work, the talk app will show an error message anyways ;)

**Comment by enoch85** [comment]
> If it won't work, the talk app will show an error message anyways ;)

As I said, it will only show if the signalling is installed and the proxy config is active. I'm fine with that.

I will try to put the logs in $VMLOGS now, after that I think we're done here. Do you have anything else?

**Review by morph027 — APPROVED** [review]
lgtm and test worked.

**Comment by enoch85** [comment]
OK all done. Will merge this when travis thinks it looks good.

Thanks guys! Really really appreciated! :1st_place_medal:

**Comment by enoch85** [comment]
@szaimen You can remove the domains now. 

Everything did some final tidying up, and everything is working like charm. :)

**Comment by szaimen** [comment]
> @szaimen You can remove the domains now.

okay, both? (cloud.lindnercloud.com & test.lindnercloud.com)

**Comment by enoch85** [comment]
Yes, if not in use ofc. :)

**Comment by szaimen** [comment]
done 👍

**Comment by enoch85** [comment]
https://www.techandme.se/its-your-turn-to-try-nextcloud-talk/

**Comment by szaimen** [comment]
@enoch85 I've just tested it on my productive machine and there was a bug:
I head to set the domain of my signaling-server manually in the talk-admin-site.
To fix this, we have to move those two lines 
https://github.com/nextcloud/vm/blob/master/apps/talk_signaling.sh#L196
https://github.com/nextcloud/vm/blob/master/apps/talk_signaling.sh#L205
after this line:
https://github.com/nextcloud/vm/blob/master/apps/talk_signaling.sh#L233
Otherwise it worked perfectly 👍

**Comment by enoch85** [comment]
Could you please make a PR? I'll merge it right away. Thanks!

**Comment by enoch85** [comment]
Please fix the typo here as well: https://github.com/nextcloud/vm/blob/master/apps/talk_signaling.sh#L431

**Pull request merged**
