### PR TITLE
Revert "fix pecl php extensions"

### PR DESCRIPTION
**Pull request by enoch85**
Reverts nextcloud/vm#1825

ouch: cannot touch '/etc/php/7.4/mods-available/igbinary.ini': No such file or directory
grep: /etc/php/7.4/mods-available/igbinary.ini: No such file or directory
/var/scripts/nextcloud_update.sh: line 304: /etc/php/7.4/mods-available/igbinary.ini: No such file or directory
/var/scripts/nextcloud_update.sh: line 305: /etc/php/7.4/mods-available/igbinary.ini: No such file or directory
WARNING: Module igbinary ini file doesn't exist under /etc/php/7.2/mods-available
WARNING: Module igbinary ini file doesn't exist under /etc/php/7.2/mods-available
Nothing to upgrade
touch: cannot touch '/etc/php/7.4/mods-available/apcu.ini': No such file or directory
grep: /etc/php/7.4/mods-available/apcu.ini: No such file or directory
/var/scripts/nextcloud_update.sh: line 346: /etc/php/7.4/mods-available/apcu.ini: No such file or directory
/var/scripts/nextcloud_update.sh: line 347: /etc/php/7.4/mods-available/apcu.ini: No such file or directory
WARNING: Module apcu ini file doesn't exist under /etc/php/7.2/mods-available
WARNING: Module apcu ini file doesn't exist under /etc/php/7.2/mods-available
Reading package lists... Done

### CODE REVIEW

**Comment by enoch85** [comment]
cc @szaimen

**Comment by szaimen** [comment]
Good think, I am going ot improve this. Obviously I forgot that there are some instances that still use php7.2

**Comment by szaimen** [comment]
On my testinstance with php7.4 it worked without any problem.

**Comment by enoch85** [comment]
Yes, not 100%... You have to be more precise. :1234: 

It's my fault who didn't test, but still. This makes me worried, did we miss on more places which I just merged without testing?

Before when I had time I did this for every change:
1. Installed a fresh VM with the fix
2. Updated an old VM with different versions of dependencies
3. Checked that I didn't get any errors in the script, Nextcloud and dependencies

Now I don't have time... :/

I fixed it in a new PR anyway. :smile:

**Comment by szaimen** [comment]
> Yes, not 100%... You have to be more precise. 🔢

I'll try do do so 👍

> It's my fault who didn't test, but still. This makes me worried, did we miss on more places which I just merged without testing?

If there would be, I guess we would have already got a report about this.
(Did you see https://github.com/nextcloud/vm/pull/1812#issuecomment-778386233 ?)

> Before when I had time I did this for every change:
> 
> 1. Installed a fresh VM with the fix
> 2. Updated an old VM with different versions of dependencies
> 3. Checked that I didn't get any errors in the script, Nextcloud and dependencies

Sounds like a lot of additional work, but obviously seems to make sense 👍

> I fixed it in a new PR anyway. 😄

Great! Thanks! :)
Now I can continue with https://github.com/nextcloud/vm/pull/1817 if notify_push is available as stable app in the appstore :)

**Comment by szaimen** [comment]
@enoch85 
https://github.com/nextcloud/vm/pull/1812#issuecomment-778386233 seems to be https://github.com/nextcloud/server/issues/24711

**Comment by szaimen** [comment]
So whenever an app is enabled this issue seems to be triggered, as far as I can see.

**Pull request merged**
