### PR TITLE
change to DNS challange instead of certonly

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by enoch85** [comment]
Need someone to test this @nextcloud/vm

**Comment by Ark74** [comment]
Hi!
I'm not aware that certbot has dns challenge capabilities, I only was aware of acme.sh

Is this it?

**Comment by enoch85** [comment]
@Ark74 

> Is this it?

Yes. :)

**Comment by enoch85** [comment]
Just tested and it works!

**Comment by Ark74** [comment]
El sáb, 17-03-2018 a las 09:56 -0700, Daniel Hansson escribió:
> Just tested and it works!
Great news!, i'll test it myself later at night.
Is this method for local devices?, where DNS won't resolve IP.
Cheers!
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   > 
>   > 

> 
> 

> 
> 
> 
<span class="-x-evo-quoted"><span class="-x-evo-quote-character">> </span></span>{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nextcloud/vm","title":"nextcloud/vm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nextcloud/vm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@enoch85 in #496: Just tested and it works!"}],"action":{"name":"View Pull Request","url":"https://github.com/nextcloud/vm/pull/496#issuecomment-373935469"}}}

**Comment by enoch85** [comment]
> Is this method for local devices?, where DNS won't resolve IP.

I haven't tested on a "local" machine, the server needs a DNS record and port 80 + 443 open for it to work. 

Just did another install for a customer with this, went flawless!

**Pull request merged**
