### PR TITLE
fix the --not-latest flag

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
Sorry, but I'd rather have it "breaking" than someone not wanting to install the latest stuff. 

If you really do want to not use the latest, then just hash out the lowest compatible, and *then* have stuff breaking. :)

**Comment by enoch85** [comment]
Thanks for remembering though.

**Comment by szaimen** [comment]
I don't get what your problem with that change is because with this change the flag works again. 
Why removing that functionality?

**Comment by enoch85** [comment]
> Why removing that functionality?

I can live with a "breaking" (it's only that function that breaks for like 2-3 point releases) change for a question that came up 1 time in 6 years to solve the real issue with NC 21 needing phone region and an updated lib file.

Sure, the alternative is to hammer the lib file and updated it all the time, but I'd rather change the structure of the script - require NC 21 and not needing to fetch the lib again.

If you really want to fix this, then lower to NC 20 for compatibility and add back the check for NC 21 in the phone region function. No need to fetch the lib again with the current structure.

I was thinking less code, but sure, if this can't be avoided, why not.

**Comment by szaimen** [comment]
> If you really want to fix this, then lower to NC 20 for compatibility and add back the check for NC 21 in the phone region function.

Isn't that exactly what I've done here? 🧐

> I was thinking less code, but sure, if this can't be avoided, why not.

Yes, would be great if we could restore the --not-latest flag functionality since I recommend to use it :)

**Comment by szaimen** [comment]
Thanks! :)

**Pull request merged**
