### PR TITLE
travis

### PR DESCRIPTION
**Pull request by enoch85**
fixing https://github.com/koalaman/shellcheck/wiki/SC2206

### CODE REVIEW

**Comment by enoch85** [comment]
@ggeorgg Could you please have another look at this? I'm on parental leave now, so I can't (don't have time) test if this works.

Thanks!

**Comment by enoch85** [comment]
OK, so it's still not working.

@ggeorgg Please have a look. Thanks!

**Comment by enoch85** [comment]
I forgot to add the array to mapfile, so was debugging something that never would work. Finally found it. :D

**Comment by ggeorgg** [comment]
I am currently quite busy with my relocation and some stuff from work. I can't help you out at the moment, sorry...

**Pull request merged**
