### PR TITLE
fix network_ok

### PR DESCRIPTION
**Pull request by szaimen**
This should harden the check here:
https://github.com/nextcloud/vm/blob/cbc20d1881f1341db2b8b231b83acfdc611278bb/nextcloud-startup-script.sh#L69

### CODE REVIEW

**Comment by szaimen** [comment]
It seems like this isn't neede since it just returns the value from site_200

**Comment by enoch85** [comment]
@szaimen What was this?

**Comment by enoch85** [comment]
Please remove the branch if you don't plan to do anything further with this.

**Comment by szaimen** [comment]
> Please remove the branch if you don't plan to do anything further with this.

done

**Pull request closed without merging**
