### PR TITLE
Adjust umask for new files

### PR DESCRIPTION
**Pull request by szaimen**
Adjust umask for new files (defaults to 0133 which gives everyone read access). Now only www-data members and user will be able to read and change new files.
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
My question is, if the UMASK is set to a default, it's for a reason. So what's the reason behind changing it?

Security sure, but are we 100% sure about the side effects?

**Comment by szaimen** [comment]
I must admit that I cannot say why it is set to 0133 but it is definitely insecure.
BTW: file creation, deletion, etc. works still fine with my PR which we should care about, no?

**Comment by enoch85** [comment]
What's the background for you adding this here then? 

Have you tested a full installation with this, all the apps and all the other things? I mean PHP-FPM is the core in the VM - if it breaks it's disaster.

**Comment by szaimen** [comment]
The idea was that all new instances profit from this security benefit. I for myself edited it in the correct file but I currently don't have the time to test sufficiently so I am going to close this for now.

**Pull request closed without merging**
