### PR TITLE
prevent apps from breaking the update due to incompatibility

### LINKED ISSUE #1834: Upgrade issue v20 -> v21: OCC no longer works because of Undefined class constant 'MAJOR_VERSION' in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Utils.php:118
## Steps to reproduce
1. Update from v20 to v21
2.
3.

## Expected behaviour
no error and nextcloud still working

## Actual behaviour
errors and nextcloud no longer working (seems occ commands fail)

## Server configuration

**Nextcloud server version:** v20 before, now v21

**Server OS** (Ubuntu server is default)
Ubuntu Server

**How did you install the VM?** (Scripted install from master **OR** Released version)
Hansson script for VM

## Network
**Do you use DHCP?**
no, static ip

**Is port 80 and/or 443 open?**
yes, both

## Logs / Screenshots

https://paste.ubuntu.com/p/wV7T34dGWk/

#### Log file (/var/log/nextcloud/nextcloud.log)
```
[nextcloud.log](https://github.com/nextcloud/vm/files/6016279/nextcloud.log)
```

#### Installation log (command output)
```
Insert the CLI output here
```

### PR DESCRIPTION
**Pull request by szaimen**
fix #1834
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
This was successfully tested by upgrading an ubuntu 20.04 testmachine from NC20.0.7 to NC21.0.0

**Comment by enoch85** [comment]
@szaimen Can you test on an old 16.04 as well? Or maybe you don't have one available?

**Comment by szaimen** [comment]
I don't have one available.

**Comment by enoch85** [comment]
So what does this do exactly?

Remove apps to be installed that are not compatible?

**Comment by enoch85** [comment]
OK, it makes sense.

https://help.nextcloud.com/t/help-what-is-app-install-overwrite-for/71523

**Pull request merged**
