### PR TITLE
updatenotification ist stable

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by enoch85** [comment]
We should leave it im the uofstes script so that everyone can get it before the new release, then make a new PR to remove it once the new release is out.

**Comment by szaimen** [comment]
Ah okay, yes you are right!

**Comment by szaimen** [comment]
> We should leave it in the updates script so that everyone can get it before the new release, then make a new PR to remove it once the new release is out.

done 👍

**Comment by enoch85** [comment]
:drum:

**Pull request merged**
