### PR TITLE
warn that apps could be incompatible before upgrading to a major version

### PR DESCRIPTION
**Pull request by szaimen**
as it was suggested here:
https://help.nextcloud.com/t/nc-20-too-many-incompatible-apps-what-to-do/93869/7

### CODE REVIEW

**Comment by enoch85** [comment]
No, better notify the user of how to re-enable untested apps, at their own risk with `notify_admin_gui` or `send_mail`since updates can be automated and that menu won't show up.

Also, we can't use that function in the update script as it would break it if running silent.

Right now we have like 1000 popups (`msg_box`) and I'm starting to think it's too much already.

**Comment by szaimen** [comment]
> No, better notify the user of how to re-enable untested apps, at their own risk with `notify_admin_gui` or `send_mail`since updates can be automated and that menu won't show up.
> 
> Also, we can't use that function in the update script as it would break it if running silent.

But major updates are not automated.
At least not by us?

**Comment by enoch85** [comment]
> But major updates are not automated.
At least not by us?

Yes, we didn't add the minor switch until after a while, so there may still be full upgrades taking place.

Also, the one in the issue was experiencing that from what I understand.

**Comment by szaimen** [comment]
Okay, didn't know that the minor switch was just added after.

No, as far as I understand, he updated manually via cli.

**Pull request closed without merging**
