### PR TITLE
suggest to change the mirror if it is the default one

### PR DESCRIPTION
**Pull request by szaimen**
as the title says. I think it was wrong before.

### CODE REVIEW

**Comment by enoch85** [comment]
I was thinking the same, but the trade off is actually worse as we can't trust the mirrors that are set in the locate_mirror script.

I will think about this a bit more.

**Comment by szaimen** [comment]
> I was thinking the same, but the trade off is actually worse as we can't trust the mirrors that are set in the locate_mirror script.

Then just set it to OFF always?

**Comment by enoch85** [comment]
Sure, but please leave the startup switch in there in case I  change my mind. :+1:

**Comment by szaimen** [comment]
> Sure, but please leave the startup switch in there in case I change my mind. 👍

done

**Pull request merged**
