### PR TITLE
Allow to pass the DIG test in some edge cases

### PR DESCRIPTION
**Pull request by enoch85**
**WIP**

### CODE REVIEW

**Comment by enoch85** [comment]
@bobdig, please test this.

**Comment by bobdig** [comment]
@enoch85 Would love to but don't know how this all works.

**Comment by enoch85** [comment]
OK, I'll merge this since I tested it here.

@bobdig Please download the latest activate-ssl.sh in about 15 minutes and run it just to see if it's possible to pass the test.

Thanks!

**Comment by bobdig** [comment]
@enoch85 So I did a fresh install and the files got downloaded automatic. There was a nice Screen showing the problem with the two different IP addresses and a solution was given. 
But also there was a screen telling me, that there is a newer version of something, so I went with the newer one. And after that the first try of creating the cert failed. But at the given second try it succeed. 
I'll send you the sreenshots.
But all in all it worked!

**Pull request merged**
