### PR TITLE
Fix downloading other files than sh files

### LINKED ISSUE #2008: master/static/index.sh
## Steps to reproduce
1. Nextcloud Install script
2.
3.

## Expected behavior
We just tried to fetch 'https://raw.githubusercontent.com/nextcloud/vm/master/static/index.sh', but it seems like the server for the download isn't reachable, or that a temporary error occurred. We will   │
│ now try again.  

## Actual behavior
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**PHP Version** (e.g. 7.4)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

### PR DESCRIPTION
**Pull request by szaimen**
Fix #2008
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
Also works, but is just a workaround. There must be a better way.

**Comment by szaimen** [comment]
Please have a look yourself then. Thats the best I was able to come up with.

**Comment by szaimen** [comment]
In my opinion it is not really a workaround because those are the only places where we have other files than .sh files. So we should be able to change the download_script function to only download sh files if not explicitely defined.

**Comment by enoch85** [comment]
Yes, but the whole idea with `download_script` and `run`script` is to be able to call any of the file endings we add. 

Right now I'm looking into if we can somehow check if any of those functions are used in `curl_to_dir`, or if we can check by the download URL if it contains php or something else. Then we could make it generic.

**Pull request closed without merging**
