### PR TITLE
change repo var

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by enoch85** [comment]
cc @Ark74

**Comment by Ark74** [comment]
So does apt-cache policy follows the source.list?
Or does it uses the software properties like add-apt-repository that are not reflected on the sources file?

At the end preferred grepping the sources.list file since apt-select modifies exactly that file.
If you find it better, it's ok with me.

**Comment by enoch85** [comment]
This isn't perfect and doesn't pick up DO for example... :/ But it's better than a empty output which the other gave sometimes becuase it's very specific and expects the 1:st line to contain the mirror address.

**Comment by enoch85** [comment]
Trying to find a failsafe method... but it's hard.

**Comment by enoch85** [comment]
Think I found it!

apt-get update | grep -m 1 Hit | awk '{ print $2}'

**Pull request merged**
