### PR TITLE
rename the NcVM-snapshot-update name to NcVM-snapshot-pending

### PR DESCRIPTION
**Pull request by szaimen**
As the title says

As you know, this doesn't effect any current OVA.
(only if explicitely chosen during the nextcloud_install_production script and it is also not the default)

### CODE REVIEW

**Comment by enoch85** [comment]
This seems unfinished... Are you sure about this?

**Comment by szaimen** [comment]
> Are you sure about this?

Yes, I am sure about this. 👍

**Comment by szaimen** [comment]
> This seems unfinished..

What lets you think this way?

**Comment by szaimen** [comment]
> > This seems unfinished..

I only renamed the snapshot name during the backup.
This doesn't change any functionality. I don't know why this should be unfinished?

**Comment by enoch85** [comment]
What about people that already chose the snapshot option? They will still have the old name.

**Comment by enoch85** [comment]
Please answer my question above :point_up_2: 

Thanks!

**Comment by szaimen** [comment]
> What about people that already chose the snapshot option? They will still have the old name.

They only have the old temporary snapshot name if the update has failed. In this case they will be able to execute the update script again but no new snapshot will be created. Imo this should be fine.

**Pull request merged**
