### PR TITLE
allow lvm snapshots

### PR DESCRIPTION
**Pull request by szaimen**
I made it possible to choose if you want to use it during the install script. It is not the default so we could test this from master, if we wanted because it will not effect people who have not setup lvm snapshots.

fix https://github.com/nextcloud/vm/issues/1522

### CODE REVIEW

**Comment by szaimen** [comment]
We should discuss whether 2.5GB will be enough. 

I made a test:
I run the install script. it takes around 1.3GB of space from the snapshot.
Afterwards I ran the startup script and installed fail2ban, Adminer, Netdata, BPytop, Fulltextsearch, Previewgenerator and Webmin. I ran it to the end incl. the update script and it took 2.7GB of space from the snapshot. So to make sure that you are able to use the snapshot as restore point during the startup script, we should most likely make it bigger than 2.5GB. I guess 5GB should be more than sufficient.

What do you think about this?

**Comment by szaimen** [comment]
btw: after running the ubuntu server installer, it has this config:
image

**Comment by szaimen** [comment]
> We should discuss whether 2.5GB will be enough.
> 
> I made a test:
> I run the install script. it takes around 1.3GB of space from the snapshot.
> Afterwards I ran the startup script and installed fail2ban, Adminer, Netdata, BPytop, Fulltextsearch, Previewgenerator and Webmin. I ran it to the end incl. the update script and it took 2.7GB of space from the snapshot. So to make sure that you are able to use the snapshot as restore point during the startup script, we should most likely make it bigger than 2.5GB. I guess 5GB should be more than sufficient.
> 
> What do you think about this?

I've changed it to 5GB. It seems to make more sense.

**Comment by szaimen** [comment]
@enoch85 since this PR is relatively short: what are you missing to merge this? I've tested this already successfully. It will not effect instances that don't use snapshots (no instances that haven't run through this new option during the install script)

**Comment by enoch85** [comment]
> since this PR is relatively short: what are you missing to merge this? I've tested this already successfully. It will not effect instances that don't use snapshots (no instances that haven't run through this new option during the install script)

I'm not sure we want this.

**Comment by enoch85** [comment]
It also touches all the most important scripts...

**Comment by szaimen** [comment]
Am I right that I cannot convince you that this PR makes sense by saying that I've made sure that this won't effect any existing install? 
It would btw also don't effect any install starting after this PR that hasn't consciously opted in during the install script...

**Comment by enoch85** [comment]
It should say, I'm not sure since I didn't test.

Now I've tested and as it's not default, and not executed if not chosen during the install script, we can merge this.

**Pull request merged**
