### PR TITLE
Xenserver/XCP Hypervisor Support

### PR DESCRIPTION
**Pull request by zalonic**
Hello,

While reviewing some bits we came across this [comment](https://github.com/nextcloud/vm/issues/535).
We have been using Xenserver and XCP for a while and thought we would post how we have been installing this on ours.

We've cloned the format-sdb.sh script and amended it to work with Xen/XCP, if it makes it easier to maintain we can merge the scripts together with some variables into one format.sh

Please let me know your thoughts.

### CODE REVIEW

**Comment by zalonic** [comment]
Okay maybe put a pin in this until we see fix the build failure.

**Comment by enoch85** [comment]
What happened here?

**Comment by zalonic** [comment]
Sorry, slight disagreement over this our end, my account was logged in so they posted the changes I had made for the Xenservers we use, however, it doesn't actually work correctly because... although it now recognised the XVDB disks and will install correctly on a Xenserver, if you try it on a standard VMware or VBox is no longer sees SDB.

I told my guy to close this until I had actually worked out how to do this correctly and then we can post it as a pull request.

Sorry about this.

**Comment by enoch85** [comment]
@zalonic No problems! Would be great if you could fix Xenserver support.

I suggest a function in the existing script, not adding another one. Looking forward to your contribution!

**Comment by penzoiders** [comment]
we should also include KVM VirtIO support (eg: `/dev/vdX` disks) let's fix this togheter.

**Comment by enoch85** [comment]
@penzoiders Sure! Been having some bug reports about Xen and it would be awesome to extend the support!

**Comment by zalonic** [comment]
Hi all, right think I've worked it out. Just making the changes and will upload as soon as I get a chance. I will modify the entire fork I have to download the scripts from my repository so we can run the install from there to test and then if all goes well I will revoke all my amendments except the disk modifications for the commit.

@penzoiders can you confirm how the disks work on KVM as I'm not familiar, are the devs xva, xvb and when partitioned xva1, xvb1, xvb2?

**Comment by zalonic** [comment]
Sometimes... I dislike people... well I've created the script and it works on HyperV and Xen, KVM is still untested as I don't know exactly how the disks are labelled in the system.

However somewhere between me posting my last comment and this one, one of my dev guys has deleted the Repo because he thought it wasn't needed [angry face].

Blocked all of them from my account now as I can't have that happening again.

Unfortunately, this means I will have to open a new pull request.

**Comment by enoch85** [comment]
@zalonic 

> open a new pull request.

No problem, you can open as many as you want ;) :+1:

**Pull request closed without merging**
