### PR TITLE
add option to disable the admin-panel for bitwarden_rs

### PR DESCRIPTION
**Pull request by szaimen**
This is ready for review. It was already sucessfully tested.

### CODE REVIEW

**Comment by enoch85** [comment]
Is this specific to RS?

I know that the official release also got an admin panel.

**Comment by szaimen** [comment]
> Is this specific to RS?
> 
> I know that the official release also got an admin panel.

Yes, this is specific to bitwarden_rs.

For official bitwarden, if you leave the global-config adminSettings__admins empty, which it is by default, nobody will have access to the its admin panel. (you can change this already in the mailconfig script)

**Comment by enoch85** [comment]
Aah ok, makes sense.

Didn't test my changes, but I think it looks cleaner.

If you can confirm it work, I'll merge. :+1:

**Comment by szaimen** [comment]
> Didn't test my changes, but I think it looks cleaner.

your changes unfortunately don't work, but I found a working solution, that I just pushed to the branch.
So it is ready to go 👍

**Comment by enoch85** [comment]
Strange since `" "` is used. But ok, it still looks better than before. :+1:

**Comment by szaimen** [comment]
> Strange since `" "` is used. 

i can try to explain it to you, if you want

**Comment by enoch85** [comment]
No worries. :)

**Pull request merged**
