### PR TITLE
Let user select the device for the nextcloud data

### PR DESCRIPTION
**Pull request by ggeorgg**
One problem I see is that the user can fill in any text. There is no input validation...

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks! 

Input validation is a must btw as this script is crucial for everything to work.

More options will also generate more errors as users probably will do it the wrong way. Let me think about this.

**Comment by ggeorgg** [comment]
I modified the commit. Please have try now. What do you think?

**Comment by enoch85** [comment]
DEVTYPE is still changed in [here](https://github.com/nextcloud/vm/pull/727/files#diff-8bff978ff8cc8677ee9420cf74d79a61R96) which means that your code won't have any effect. Please make it an option instead. Like; "Would you like to choose your own disk, or would you like to choose the second disk automatically?"

Also please fix the travis errors: https://travis-ci.org/nextcloud/vm/builds/461460259?utm_source=github_status&utm_medium=notification

**Comment by enoch85** [comment]
Sorry, I was a bit tired this morning. It says DISKTYPE, not DEVTYPE. :)

**Comment by enoch85** [comment]
Actually, when thinking about it, I think it's better to make this a seperate script and ask the user which script to run. 

1. Automatically = format-sdb.sh
2. Choose yourself = format-chosen.sh

**Comment by ggeorgg** [comment]
I think it's not worth to make another script. It's not that much code and it's not a completly other thing. So I would leave it in this script here.
The new lines need to be after the "checks what Hypervisor disks are available" because I wanted to have a default value for DEVTYPE.

**Comment by enoch85** [comment]
OK, I haven't tested this, have you?

Why I would want a second script is because it's easier when if comes to the IF argument. Adding this adds more complexity which also raises the risk of a failure. The whole logic changes with this change, so it would be easier to separate it into two scripts, where you can have two different logic's.

Makes sense?

**Comment by ggeorgg** [comment]
I added another script. I am not that happy with this solution because there is to much redundant code now...

**Comment by ggeorgg** [comment]
I have just tested the code snipped in a tests file, but not yet the whole script.

**Comment by enoch85** [comment]
That's not what I meant at all.

I can do the changes and you can test them. I'll have a look later today.

**Comment by enoch85** [comment]
Sorry, the diffs weren't updated. That's a correct change.

**Comment by enoch85** [comment]
@ggeorgg I tested he script now and it seems to work. If you are willing to maintain format-choosen.sh then I will merge this. I that OK by you?

**Comment by ggeorgg** [comment]
I will give my best ;)

**Pull request merged**
