### PR TITLE
update ssh instructions for windows

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by enoch85** [comment]
Good point and I like it! Problem is, what if you're not running Windows 1809 or later?

**Comment by szaimen** [comment]
> Good point and I like it! Problem is, what if you're not running Windows 1809 or later?

Then you can use putty. Thats the reason why I haven't deleted those putty referring lines ;-)

**Comment by enoch85** [comment]
I'm sorry to say that the text doesn't fit a console window.

Please narrow it down. Run the script inside both a Putty window, and a VMware / Hyper-V console window to see if t fits.

**Comment by szaimen** [comment]
HM, that is not a problem on my system:
image
image

But I trust you if you say so.

What about this:

> To be 100% sure that all the keystrokes work correctly (like @),     
> please use an SSH terminal like Putty. If you are running Windows 
> 10 1809 or later, you can simply use SSH  from the command prompt.                                             
> Connect like this: ssh ncadmin@local.IP.of.this.server

**Comment by enoch85** [comment]
Hmm, ok, let's merge it then. It didn't fit my Linux CLI prompt which I count as standard. ;)

**Pull request merged**
