### PR TITLE
Fix variables on occ command

### PR DESCRIPTION
**Pull request by Ark74**
This should fix the static values for the variables on the occ command.
Cheers!

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks, but please but all the varbles in lib.sh.

**Comment by Ark74** [comment]
Well, the command is inside hard quotes, that's why I tried this way.
I'll think on something.

Please any other idea is pretty welcome. :)

**Comment by enoch85** [comment]
A much cleaner solution :)

**Comment by enoch85** [comment]
Will have to test the quoting later.

**Comment by enoch85** [comment]
Fixed quoting. Everything expands correctly.

**Pull request merged**
