### PR TITLE
Fix cookielifetime

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 This works!

**Comment by enoch85** [comment]
Sorry, I meant to do a PR but pushed to master instead. OOPS! :D

**Comment by enoch85** [comment]
Please test the new fix

**Comment by szaimen** [comment]
I have already done this. And it is working 👍

**Comment by enoch85** [comment]
Great minds think alike! :D

**Pull request closed without merging**
