### PR TITLE
20.0.1

### PR DESCRIPTION
**Pull request by enoch85**
@szaimen Please add the stuff you changed.

I will have a look soon. 

Thanks!

### CODE REVIEW

**Comment by szaimen** [comment]
I think those should be all ;)

**Comment by enoch85** [comment]
Perfect! Thanks @szaimen!

**Comment by szaimen** [comment]
Wow, I am amazed!
Travis finally finished after 2 days 😅

**Comment by szaimen** [comment]
@enoch85 When do you want to do the release?

**Comment by TheNomad11** [comment]
Sorry for interrupting you, but I got your 20.0.1 update already last weekend? It did not show up under releases, that was weird, though!

**Comment by enoch85** [comment]
> that was weird, though!

Haha, not that weird since I never announced it.

When I make the final release, then, and only then I publish it here on Github as well, in the docs, and all that. :)

**Comment by TheNomad11** [comment]
> > that was weird, though!
> 
> Haha, not that weird since I never announced it.
> 
> When we make the final release, then, and only then I publish it here on Github as well, in the docs, and all that. :)

So in the automatic updates we get beta versions?

**Comment by enoch85** [comment]
> So in the automatic updates we get beta versions?

No? I don't think I understand...

**Comment by TheNomad11** [comment]
> > So in the automatic updates we get beta versions?
> 
> No? I don't think I understand...

Last weekend I got a NC-notification that 20.0.1 is ready, then I ran your update script and since then I have been using 20.0.1 although you have not released it officially and it does not seem to be stable? Everything seems to work fine, though

**Comment by enoch85** [comment]
@TheNomad11 Naah, the released version here isn't downloaded by the update script. The update script updates the already existing Nextcloud and it's dependencies, it doesn't fetch the release from this repo.

A release in this term, means that we make 20.0.1 available for every new download. There are people that downloaded NC 10, and are now on NC 20 with the update script, but they don't have to get a new release from here every time. That's part of the beauty with the update script. :)

**Pull request merged**
