### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by unamundan**
- Overall: I tried to hack _(condense)_ existing content if only minimally to shorten read time, fixing a few errant typos along the way.
- This step could use some clarification: “Run update.sh but abort it before it starts so that you have the latest nextcloud_update.sh. Then put this in your nextcloud_update.sh below the curl command (lib.sh) but before everything else and run it:”
- The answer “If you want automatic updates of both Ubuntu and Nextcloud ... ” points to a blog post that does address NC but doesn’t seem to address *Ubuntu.*

Thanks for all your hard work, Daniel! Take any or leave all of these submitted revisions without fear of disappointing the editor. My only goal was to provide minor alterations that may or may not boost content fluidity and comprehension.

— Submitted respectfully

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks!

Maybe you could have a look at this as well while your at it? https://github.com/nextcloud/vm/issues/805

**Comment by enoch85** [comment]
@unamundan Let's keep the discussion here.

**Comment by unamundan** [comment]
@enoch85 —  My first down-and-dirty pass at the README was spent most tweaking _what was already there_. With the new idea that the whole document might stand reworking, I’m massaging markdown locally and will post fresh sections as I’m satisfied they’re ready, or at least ready for review. I worked on opening explanatory copy tonight and posted those results. Review from the top through “All Systems Go.” The idea is to keep the opening higher-level. Lower level details will follow. I think this is a good first step to explain OVERALL what NVM does. The section which follows will explain in more detail the _variety_ of ways to setup a system.

**Comment by unamundan** [comment]
@enoch85 —

If we consider the possibility that @bish0polis’s [confusion](https://github.com/nextcloud/vm/issues/805) is shared by others, a rebranding discussion may be valuable and relevant as we rewrite the README. While Nextcloud VM _can be_ a VM, it also _isn’t._ On the one hand, there are _preconfig’d VMs_. On the other hand, there are _simply scripts._  Because (a) the foundational scripts can be used _outside_ of the preconfig’d, downloadable VMs, (b) the scripts can be utilized on _virtualized **and** real_ hardware, and (c) individual scripts can be run independent of the master “production” script ... you might consider the possibility of changing the product’s name.

What _is_ universal here ... what’s true of _this “thing”_ ... in _all_ cases ... are the underlying scripts. They collect and stitch together. They cobble, or sew, together a puzzle of items into a whole. Book binders create a codex from many pages. Tailors alter and stitch together a full garment. Concierges and valets collect and distribute useful information and services. Etc.

I’m not professing that these are _solutions_ but, rather, an attempt to capture words that conjure more broadly what exactly is happening:

Nextcloud Concierge
Nextcloud Valet
Nextcloud Nimble
Nextcloud Assembler
Nextcloud Scripter
Nextcloud Conductor
Nextcloud Stitch
Nextcloud Bindery
Nextcloud CodeX
Nextcloud DNA
Nextcloud Tailor
Nextcloud Weaver

I’m also not asserting that “Nextcloud VM” should necessarily be replaced.

**Comment by enoch85** [comment]
Great work so far! Thanks! 

Please move "Support the development"-section to the second block.

Regarding it being used as a VM or a with the scripts - the scripts *are* the VM since it's built upon it. At the same time the pre-configured VMs are a way to simply pay a small fee (or download for free) to get a completely hassle free install. Just mount it and voilá - you have your server. Also, the pre-configured paid options are a small income to keep the development ongoing. So, leaning towards DYI with the scripts or leaning towards the pre-configured VMs, my choice would be to enhance the text regarding the VMs as it would pay for the development.

Maybe change the text from Build it yourself to, "Are you feeling brave? - Build it yourself" or similar. Makes sense?

**Comment by enoch85** [comment]
Hey @unamundan Is this ready to merge?

Thanks for your efforts so far!

**Comment by enoch85** [comment]
I'm happy with this. Please let me know if you want to make other changes @unamundan 

Otherwise I will merge in about 5 days.

**Comment by unamundan** [comment]
Hey @enoch85 — The introductory section was the-most-heavily sculpted. After that section, regarding _my_ contributions, it’s still all _VERY_ rough. I started down one path (namely, “just tweak what’s there) but realized I probably needed to veer in another (rewrite with an eye for beginners and details). Being a newbie to markup and excited to try it, I think I may have done at least one thing that will negatively impact mobile / handheld readability: the table at the top.

I have a LOT of temporary copy and details I’m still fleshing out that I haven’t posted yet. If you must merge, go ahead. But if it _can_ wait ... _do, please._ You’ll know best whether it’s preferable to roll out revs in waves or wait until a full rewrite is complete. I’d lean toward the latter, but there may be reasons I’m unaware of which would dictate the opposite.

I went from having some time to focus on the rewrite to having _NONE!_ That should change here in the next few days and I’ll continue where I left off.

**Comment by enoch85** [comment]
I must not merge, just haven't heard from you in a while, hence my question. :)

Feel free to add more stuff and let me know when you are satisfied.

**Comment by unamundan** [comment]
Will do. Sorry I’ve been and still am absent. Working like crazy. Pushing nextcloud _hard_ and it hasn’t broken. _Yet._  :sweat: When I get a break, I look forward to continuing.

**Comment by enoch85** [comment]
> Pushing nextcloud hard and it hasn’t broken.

I'm glad the the installation we did works out for you!

**Comment by enoch85** [comment]
I will merge this now. You can work on another PR later on. No stress. :)

**Pull request merged**
