### PR TITLE
Update Additional Apps

### PR DESCRIPTION
**Pull request by szaimen**
and fix typo in the startup script

### CODE REVIEW

**Comment by enoch85** [comment]
:+1:

**Comment by szaimen** [comment]
@enoch85 The Travis Error is a bit annoying and not caused by my PRs... Could you please fix it and merge the Master afterwards into all my PRs?

**Comment by szaimen** [comment]
This doesn't really have to be tested, hence marking as ready for review.

**Comment by szaimen** [comment]
We could fix the travis error here, merge the PR and merge the Master into all other PRs afterwards?

**Pull request merged**
