### PR TITLE
create nextcloud_vm

### PR DESCRIPTION
**Pull request by szaimen**
for now two questions:

Do we want to verify the state of the downloaded package with a checksum?
what is a good place where to download the .tar file to?

### CODE REVIEW

**Comment by szaimen** [comment]
concerning this script, I mean we could include everything inside this into the install_production script. But i thought it would be good for making sure that this one file is as shown (you can compare it manually) so it should be as short as possible.
I mean otherwise the user could get the instructions if he wants to be absolutely sure to download the signed release file, extract the startup script and run the install_production script but I thought it would be good to have it in a separate file...

**Comment by woa7** [comment]
> Do we want to verify the state of the downloaded package with a checksum?

IMHO: it must verify the downloadeds with at least checksum, 
or better verify it with gpg.

**Comment by woa7** [comment]
> what is a good place where to download the .tar file to?

the normal place is /tmp,
best used with mktemp like
downloaddirVAR=$(mktemp -d -t NCVM.XXXXXX)
or
downloaddirVAR=$(mktemp -d)
(both work with the GNU coreutils and also with busybox only)

**Comment by szaimen** [comment]
> IMHO: it must verify the downloadeds with at least checksum,
> or better verify it with gpg.

That was the plan 👍

**Comment by szaimen** [comment]
> the normal place is /tmp,
> best used with mktemp like
> downloaddirVAR=$(mktemp -d -t NCVM.XXXXXX)
> or
> downloaddirVAR=$(mktemp -d)
> (both work with the GNU coreutils and also with busybox only)

Thanks! I will look into it later on!

**Comment by szaimen** [comment]
superseded by https://github.com/nextcloud/vm/pull/1162

**Pull request closed without merging**
