### PR TITLE
Automate ReadOnlyRest plugin download (version)

### LINKED ISSUE #550: Automate plugin download for readonlyrest
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/releases

We can use one of the current functions like [this](https://github.com/nextcloud/vm/blob/master/lib.sh#L89) for example and fine tune it. 

cc @Ark74

### PR DESCRIPTION
**Pull request by enoch85**
Fix #550

### CODE REVIEW

**Comment by enoch85** [comment]
@Ark74 Please add your ideas here when you have time. No rush to merge.

@nxtester Please test this PR.

@daita FYI.

**Comment by enoch85** [comment]
``` 
ng readonlyrest...
+ wget -q -T 10 -t 2 https://api.github.com/repos/sscarduzio/elasticsearch-readonlyrest-plugin/zipball/v1.16.21_es6.3.0 -P /tmp/fulltextsearch-files
+ '[' -d /usr/share/elasticsearch ']'
+ cd /usr/share/elasticsearch/bin
+ check_command ./elasticsearch-plugin install https://api.github.com/repos/sscarduzio/elasticsearch-readonlyrest-plugin/zipball/v1.16.21_es6.3.0
+ ./elasticsearch-plugin install https://api.github.com/repos/sscarduzio/elasticsearch-readonlyrest-plugin/zipball/v1.16.21_es6.3.0
-> Downloading https://api.github.com/repos/sscarduzio/elasticsearch-readonlyrest-plugin/zipball/v1.16.21_es6.3.0
[=================================================] 100%   
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-6685729086745363262/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:163)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:592)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:717)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:641)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:225)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:210)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:79)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
+ printf '\e[0;91mSorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!\e[0m\n'
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
+ echo './elasticsearch-plugin install https://api.github.com/repos/sscarduzio/elasticsearch-readonlyrest-plugin/zipball/v1.16.21_es6.3.0 failed'
./elasticsearch-plugin install https://api.github.com/repos/sscarduzio/elasticsearch-readonlyrest-plugin/zipball/v1.16.21_es6.3.0 failed
+ exit 1
```

**Comment by enoch85** [comment]
Also the ports doens't seem to be open when the curl check happens, had to comment them out in my tests.

**Comment by enoch85** [comment]
But t sure seems to be open...

```
root@nextcloud:/usr/share/elasticsearch/bin# nmap localhost 

Starting Nmap 7.01 ( https://nmap.org ) at 2018-06-20 20:20 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000050s latency).
Other addresses for localhost (not scanned): ::1
Not shown: 994 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
80/tcp    open  http
443/tcp   open  https
3306/tcp  open  mysql
9200/tcp  open  wap-wsp
10000/tcp open  snet-sensor-mgmt

Nmap done: 1 IP address (1 host up) scanned in 1.63 seconds
root@nextcloud:/usr/share/elasticsearch/bin# 
```

**Comment by enoch85** [comment]
@nxtester Now you have some pointers on where to start looking if you want to contribute and fix things. Just download a fresh VM and use that for testing. That's what I always do. :)

**Comment by Ark74** [comment]
Good call! @enoch85 
I would do the same first check for the latest available plugin and then check for the latest available versions on the repository, nevertheless in order to remove the apt-mark hold we should compare both the plugin version vs. repository version, something like:
```
DEB_VERSION=$(apt-cache show elasticsearch | grep Version | cut -d ' ' -f2)
if [[ "${DEB_VERSION}" =~ "${ES_VERSION}" ]]; then
   echo "The latest version available for use is: $ES_VERSION"
elif
 [[ !"${DEB_VERSION}" =~ "${ES_VERSION}" ]]; then
        echo "There is no available package, weird, righ?"
        echo "Is ES already installed?"
fi
```

Then we would have always the latest available. The issue is that it is too bleeding edge, and we might fall into several issues of integration for early releases.

**Comment by Ark74** [comment]
Nevermind, I just realize that apt-mark hold is necessary and we need to manually trigger the ES upgrade, in other to prevent breakage.
:disappointed:

**Comment by nxtester** [comment]
@enoch85 
Sorry, I am a Linux noob, so don't expect too much :-) Actually I don't know what to test and will carefully check this thread until I have more informations. Then I am ready to test and give feedback.

**Comment by enoch85** [comment]
@Ark74 Did you have time to have a look at this yet?

**Comment by Ark74** [comment]
@enoch85 not yet I'm looking at loolws right now, I have this on my ToDo list after I'm done there. Hopefully soon.

**Comment by Ark74** [comment]
Well, seems that I've found the issue with the readonlyrest, please see here:

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/216#issuecomment-312644855

The build package from the "email" is ~14MB and the github one (same name) is ~4MB.
So seems that we should find another way to accomplish automation :disappointed:

**Comment by Ark74** [comment]
I'm looking at docker, maybe building and pulling a prebuild docker image would have better "upgrade" process and control on latest releases, just a thought since I'm not an expert on Docker.
I'll be taking a closer look, cheers!

**Comment by enoch85** [comment]
Closing this in favor of https://github.com/nextcloud/vm/pull/587

**Pull request closed without merging**
