### PR TITLE
Support for Xen Hypervisors

### PR DESCRIPTION
**Pull request by zalonic**
Added support for Xen Hypervisors

Script now checks what disks it can find and adjust the rest of the script accordingly when installing the VM manually.

This will not resolve the drive issue when importing the current OVA as this is built using SDB. I can create OVA's for Xen XVDB if required.

### CODE REVIEW

**Comment by enoch85** [comment]
Great! Much cleaner solution. Needs testing. 

@penzoiders What do you think?

**Comment by penzoiders** [comment]
Yes, that's the solution I think.
I'm not able to edit it (w/o pulling from my fork) so if you can add:
```bash
if partprobe /dev/vdb &>/dev/null;	#KVM Hypervisor
then
DEVTYPE=vdb
fi
```
That would do the trick also for KVM.


It's still limited to the second drive only, but for now is OK (Rome wasn't built in a day).
We'll eventually add more complex disk config scenarios later on if needed, for now it's OK `/dev/?da` is for system `/dev/?db` for data. So far so good.

**Comment by zalonic** [comment]
@penzoiders Amended as requested.

**Comment by enoch85** [comment]
@penzoiders Still needs testing, and I've been travelling the last couple of days. Have you tested it?

For me, it's most important that it works with VMware and Hyper-V.

**Comment by enoch85** [comment]
Btw @penzoiders, tried to add you to the team but Github says you're not a member?

image

**Comment by zalonic** [comment]
My guys are spinning up several Xen, HyperV, Vmware & Virtualbox machines and running tests on them now, I will advise when they have completed... Successfully or not.

We don't have KVM but got one of my guys looking into setting one up to test for future code changes.

**Comment by enoch85** [comment]
@zalonic, you're awesome!

**Comment by penzoiders** [comment]
> Btw @penzoiders, tried to add you to the team but Github says you're not a member?

Maybe because I've said too many bad things about Microsoft in my life and now I'm doomed to the Github ghost membership of the damned.
Let me check If I have some strange setting in the profile and I'll come back to you.


> We don't have KVM but got one of my guys looking into setting one up to test for future code changes.

If the script works for xen with `xvdX` devices it will just work for `vdX` devices from virtio KVM drivers 100% sure.

**Comment by penzoiders** [comment]
Don't really know why I wouldn't be a Github member. Any clues? I'm not that active on github, I use a private GitLab instance so I didn't have chance to notice before this issue of my account. Anyway I'll try to test the script  for KVM tomorrow If I find decent amount of spare time.

**Comment by enoch85** [comment]
@penzoiders Maybe if you accept the invitation to collaborate? It says your invitation is pending.

**Comment by enoch85** [comment]
@jospoortvliet Maybe if you can check if @penzoiders needs to be a member of @nextcloud in some way?

**Comment by enoch85** [comment]
Ok, I feel confident, let's merge this!

Thank you very much for your contribution @zalonic!

**Comment by Serghei002** [comment]
Hello gentlemen's, the problem is still there with Xenserver 7.5

**Comment by Serghei002** [comment]
Can someone help me with a version that works on Xenserver, please?
Thanks

**Comment by zalonic** [comment]
Hi Serghei002,

That's odd... It works for us?!? Could you post a screenshot of the error message you are getting.

I have raised this as a job for is to tested on Xen 7.5
Thanks

**Comment by Serghei002** [comment]
xenerror
xenerror1

**Comment by Serghei002** [comment]
The errors, Thanks

**Comment by Serghei002** [comment]
Sorry, there were two lines that can not be seen in the print screen.

Testing if network is OK...
Online!
/dev/fd/63: line 622: [: : integer expression expected
/dev/fd/63: line 658: [: : integer expression expected

**Comment by zalonic** [comment]
Did you build this VM from the installation script or import the OVA?

**Comment by Serghei002** [comment]
I imported the OVA

**Comment by enoch85** [comment]
@Serghei002 So this is when you tried to update, not running the installation script?

**Comment by enoch85** [comment]
Please post the output of `sudo ls -l /mnt/ncdata`

**Comment by enoch85** [comment]
@Serghei002 What @zalonic said ---^

**Comment by Serghei002** [comment]
sorry for the delayed confirmation,
I have ran the script on a newly installed ubuntu and everything is ok.
Thanks @enoch85 and @zalonic

**Pull request merged**
