### PR TITLE
standarlize nextcloud_occ

### PR DESCRIPTION
**Pull request by enoch85**
Signed-off-by: enoch85 <github@hanssonit.se>

### CODE REVIEW

**Comment by enoch85** [comment]
@szaimen This way, commands can be run both in code and in CLI without any changed. IMHO it's better to change in code than changing the Alias.

Any objections?

**Comment by enoch85** [comment]
Please change to `nextcloud_occ` in your PRs - I'll go ahead and merge this.

**Comment by szaimen** [comment]
@enoch85 I like this change!
BTW: I think the correct word is standardize and not standarlize ;)

**Comment by enoch85** [comment]
> BTW: I think the correct word is standardize and not standarlize ;)

:D

**Comment by enoch85** [comment]
Fun fact, this is the 800:th PR. :partying_face:

**Comment by szaimen** [comment]
BTW: all my PR's are already updated to fit the new nextcloud_occ and to resolve conflicts

**Pull request merged**
