### PR TITLE
force installation of Issue Template

### PR DESCRIPTION
**Pull request by enoch85**
Tested and works

### CODE REVIEW

**Comment by enoch85** [comment]
@juliushaertl I don't know if there's a reason for not fixing this in core(?), but this works as a workaround to get it enabled.

Please advice.

**Comment by enoch85** [comment]
@juliushaertl I don't know if there's a reason for not fixing this in core(?), but this works as a workaround to get it enabled.

Please advice.

**Comment by szaimen** [comment]
As an advice: I suppose `nextcloud_occ app:install issuetemplate --force` would probably be better ;)

**Comment by enoch85** [comment]
Aah, true, didn't know that `--force` existed.

**Comment by enoch85** [comment]
But, it didn't work. :/

**Comment by szaimen** [comment]
> But, it didn't work. :/

Strange, thats excactly the usecase it was implemented for...

**Comment by enoch85** [comment]
> Strange, thats excactly the usecase it was implemented for...

Maybe a bug, or it simply doesn't allow enabling when info.xml is wrong?

**Comment by szaimen** [comment]
Don't know... See https://github.com/nextcloud/server/pull/26252 for the PR

**Comment by szaimen** [comment]
ah, I guess it should be `nextcloud_occ app:install issuetemplate force`

**Comment by enoch85** [comment]
I'll merge this for now.

**Comment by szaimen** [comment]
Just tried the force command myself.
The force option really didn't work but what works is this:
```shell
nextcloud_occ app:install --force --keep-disabled issuetemplate
nextcloud_occ app:enable issuetemplate --force
```

**Pull request merged**
