### PR TITLE
set MTU to 1400

### PR DESCRIPTION
**Pull request by enoch85**
Fixes https://github.com/nextcloud/vm/issues/92

cc @razorfish-sl

### CODE REVIEW

**Comment by enoch85** [comment]
Tested and works!

**Comment by Ark74** [comment]
Shouldn't the comment be on the previous line?
I've had some issues in the past with comments on the same line on /etc/network/interfaces

Cheers.

**Comment by razorfish-sl** [comment]
ok, setting the MTU should not be done like above fix

something like:

pre-up  ip link set dev $IFACE  mtu 1430

but it must only be for "real" interfaces  not the loopback.

**Comment by enoch85** [comment]
@razorfish-sl

I got this:

> ok, setting the MTU should not be done like above fix

something like:

pre-up ip link set dev $IFACE mtu 1430

but it must only be for "real" interfaces not the loopback.

in my email, but nothing here. Can you make a PR please?

**Comment by razorfish-sl** [comment]
yep , i got some emails as well but nothing in the repository

**Comment by enoch85** [comment]
@razorfish-sl Where should I set `pre-up ip link set dev $IFACE mtu 1430`? Can you make a PR please?

**Pull request merged**
