### PR TITLE
simplify logic of apps re-enabling

### LINKED ISSUE #2113: Improve apps re-enabling
From this issue: https://github.com/nextcloud/vm/issues/2109

*Instead of modifying the mentioned logic, I'd vote for simplifying it instead after nextcloud/server#29020 is merged, backported and released...*

### PR DESCRIPTION
**Pull request by szaimen**
Close #2113

Disclaimer: I didn't test this.

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
Aah, ok, so we'll let Nextcloud handle this, and only copy unsupported apps to the apps folder for easier re-anbling by the user?

Are you sure we don't need to restore apps-status and all that?

**Comment by szaimen** [comment]
> Aah, ok, so we'll let Nextcloud handle this, and only copy unsupported apps to the apps folder for easier re-anbling by the user?
> 
> Are you sure we don't need to restore apps-status and all that?

Yes, thats excactly what https://github.com/nextcloud/server/pull/29020 has finally fixed ;)

**Comment by enoch85** [comment]
Tested and working!

**Comment by enoch85** [comment]
@szaimen Been having this in master now for a while and I have noticed that even core apps are missing/not enabled during update.

We now got several reports regarding this, so I really think we should improve this.

Something like:

1. Backup all current apps before the upgrade
2. Do the update
3. Check which apps that aren't enabled from the list in 1
4. Try to enabled all apps from the list in 3
5. If it doesn't succeed, ask to restore them (disabled)

That would guarantee that users easily can at least decide to enable the apps again through the GUI after a major upgrade were multiple apps are disabled. I don't trust Nextclouds app update/restore mechanism,.. :)

**Comment by szaimen** [comment]
I am not sure about this. Shouldn't https://github.com/nextcloud/vm/blob/0a3f0c661924f26ecb428ffa6fb4be52cbe3d088/nextcloud_update.sh#L1076-L1096 already do as suggested?

**Comment by enoch85** [comment]
You're right, sorry should have tested first.

**Pull request merged**
