### PR TITLE
always update minor before major version

### PR DESCRIPTION
**Pull request by enoch85**
This improves stability of the update, and covers the cases when Nextcloud makes a X.**X**.XX release.

### CODE REVIEW

**Comment by enoch85** [comment]
cc @szaimen What do you think?

**Comment by szaimen** [comment]
Sry for my late answer.

In general this should not be needed but I get where the idea comes from

**Comment by enoch85** [comment]
When NC released 22.X.1 then this is needed to since the script can't handle point releases which contains a "major feature" release.

**Comment by enoch85** [comment]
> In general this should not be needed but I get where the idea comes from

https://github.com/nextcloud/vm/issues/2261#issuecomment-1069080250

**Comment by szaimen** [comment]
> > In general this should not be needed but I get where the idea comes from
> 
> [#2261 (comment)](https://github.com/nextcloud/vm/issues/2261#issuecomment-1069080250)

alright 👍

**Pull request merged**
