### PR TITLE
create nextcloud_vm

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 I need help here: the idea is to have this one script, that just has to get downloaded once and works without needing other resources like lib.sh

for now two questions:
- Do we want to verify the integrity of the downloaded package?
- what is a good place where to download the .tar file to?

**Comment by enoch85** [comment]
In such a big change I think it's better to change the lib location to your repository first, just to be able to test all the changes before we push to master.

If this is breaking it's catastrophic.

**Comment by szaimen** [comment]
we don't change the lib location: please look at https://github.com/nextcloud/vm/pull/1120/files#diff-90b7ea30bc531dd051547e9ec21aeb32R19-R21

**Comment by szaimen** [comment]
Actually this script will be a bit like cloning the repo to "$SCRIPTS"
but first we will download the release tar file and check the integrity

**Comment by szaimen** [comment]
@enoch85 Please could you answer those two questions:

- Do we want to verify the state of the downloaded package with a checksum?
- what is a good place where to download the .tar file to?

**Comment by szaimen** [comment]
closing in favour of https://github.com/nextcloud/vm/pull/1126

**Pull request closed without merging**
