### PR TITLE
Install Docker CE

### PR DESCRIPTION
**Pull request by enoch85**
Fixes https://github.com/nextcloud/vm/issues/159

cc @oparoz

### CODE REVIEW

**Comment by enoch85** [comment]
The docker commands should be the same I guess, have not tested.

**Comment by enoch85** [comment]
@oparoz Did you run the whole script? I mean did you try to install Collabora?

I'm asking because we recently added a fix for aufs, and I don't know if the commands have changed in the `ce` version.

**Comment by oparoz** [comment]
In my experience, the commands haven't changed.
I can't install Collabora using the script as it only works with Let's Encrypt.

**Comment by enoch85** [comment]
I get `access forbidden` when installing Collabora with this. Needs more testing.

**Comment by oparoz** [comment]
It's probably unrelated, the VHOST defined in the script needs to be updated for CODE 2.0

**Comment by enoch85** [comment]
@Ark74 @ezraholm50 Can you test this please?

**Comment by Ark74** [comment]
Sure. I'm 30 minutes away from kb.

**Comment by enoch85** [comment]
It works, but the VM must be rebooted first due to something with System Dduring upstart

**Comment by Ark74** [comment]
I'm about to finish the test. I'll report

**Comment by Ark74** [comment]
Not sure why but i'm getting
cp

Even when my.ncserver.net is working with https

**Comment by Ark74** [comment]
md5sum nextcloud_install_production.sh 
`3693d967c0cc626c8a61b8f9ebf22332  nextcloud_install_production.sh`

md5sum collabora.sh 
`7d6ae88b5c4fc710a03dce695670d3a7  collabora.sh`

**Comment by enoch85** [comment]
@Ark74 Unrelated I think. It's checking your external IP. Maybe a firewall issue?

**Comment by Ark74** [comment]
Don't think so.
It's a VPS and also i have SSL conections to the server.

**Comment by enoch85** [comment]
@Ark74 `wget https://raw.githubusercontent.com/nextcloud/vm/7cbaf12551dcc9d293d28d5182d5f93c3bacc812/static/collabora.sh` and try with that file

**Comment by enoch85** [comment]
Works here. Ok to merge for me...

**Comment by enoch85** [comment]
Also tested to install several times with everything already configured and it still works. No double loading of aufs or docker settings. Yay.

**Comment by enoch85** [comment]
Let's get this in.

**Pull request merged**
