### PR TITLE
Update smb-mount and cookielifetime with new option and whiptail

### PR DESCRIPTION
**Pull request by szaimen**
fix https://github.com/nextcloud/vm/issues/1065

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 this should be ready for review

**Comment by enoch85** [comment]
radiolists are done differently in other places: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L160-L180

How is this better?

**Comment by enoch85** [comment]
Tested CookieLiftime and it works! 

Thanks @szaimen 

Though, I'm still wondering about the change from standard?

**Comment by szaimen** [comment]
> radiolists are done differently in other places: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L160-L180
> 
> How is this better?

I just like it more: doing it everywhere the same: you have continuity between msg_box -> inputbox -> radiolist -> checklist.

**Comment by szaimen** [comment]
> Tested CookieLiftime and it works!
> 
> Thanks @szaimen
> 
> Though, I'm still wondering about the change from standard?

I hope my comment above explains it.
otherwise here is a more complete view:
https://github.com/nextcloud/vm/issues/1058#issuecomment-578426862

**Comment by enoch85** [comment]
OK, let's merge this, if it works nice, then we'll change in other places as well.

**Pull request merged**
