### PR TITLE
choose port with deSEC

### PR DESCRIPTION
**Pull request by enoch85**
TODO: 

~~- Check for NONO ports~~

### CODE REVIEW

**Comment by enoch85** [comment]
FYI @peterthomassen @szaimen

**Comment by peterthomassen** [comment]
I like the idea of choosing a port for Talk -- but I'm not sure: what does it have to do with deSEC or dedyn.io?

**Comment by enoch85** [comment]
> I like the idea of choosing a port for Talk -- but I'm not sure: what does it have to do with deSEC or dedyn.io?

I needed to fix the Talk script as well to be able to make the check a function.

We will now offer users to choose port directly in the setup so that they don't have to manually change the listening port in Apache - which defaults to 433.

**Comment by enoch85** [comment]
@peterthomassen I guess this is the what you're looking for: https://github.com/nextcloud/vm/pull/1960/files#diff-30b7465f5e2121a291f1b4ddb20cd4af5d64189ec2001a9ad0a5ed4e0c69d568R230

**Pull request merged**
