### PR TITLE
fix version_gt

### PR DESCRIPTION
**Pull request by szaimen**
Sry you were too fast with merging.
version_gt isn't working correctly without that.

### CODE REVIEW

**Comment by szaimen** [comment]
BTW: the ssh fingerprint seems to have changed after the last reboot of the startup-script. 
Is it meant to be this way?

**Comment by enoch85** [comment]
> BTW: the ssh fingerprint seems to have changed after the last reboot of the startup-script.
Is it meant to be this way?

Yes for security, otherwise all thousands of users would have the same SSH-key fingerprint. :)

And thanks for the fix!

**Comment by enoch85** [comment]
All done?

**Comment by szaimen** [comment]
> Yes for security, otherwise all thousands of users would have the same SSH-key fingerprint. :)

ah okay, makes sense 👍

**Pull request merged**
