### PR TITLE
Update format-chosen.sh

### PR DESCRIPTION
**Pull request by omnidelic**
Add a test for "Intel(R) Client Systems" in line 49 to recognize Intel NUC

### CODE REVIEW

**Comment by Haxy89** [comment]
Should resolve https://github.com/nextcloud/vm/issues/1248

**Comment by enoch85** [comment]
Thanks for this PR!

>  to recognize Intel NUC

Please put it on a separate line. This would recognize the NUC as "Digitalocean" which is incorrect.

**Comment by enoch85** [comment]
@omnidelic Did you mean to close the PR?

**Comment by omnidelic** [comment]
Yea, couldn't figure out how to back out the first commit so deleted that branch and submitted a new PR.

**Pull request closed without merging**
