### PR TITLE
Integrante Nextant app

### PR DESCRIPTION
**Pull request by Ark74**
Hi,
I would like to submit this script that install solr and setup nextant app.
Feedback is welcome.
Cheers.

### CODE REVIEW

**Comment by Ark74** [comment]
How to just make a pull request for the last commit? 
(1d6a237)

**Comment by enoch85** [comment]
Ok, I will merge this, but I will not integrate it automatically, not even download the script to begin with. This needs some testing first. 

Thanks for your PR! :)

**Comment by enoch85** [comment]
@Ark74 Also, please add some testing and if arguments that exits on failure. Don't expect it to work every time.

**Comment by Ark74** [comment]
Sure, i'll keep adding some scripting to check and exit on error.
This sketch runs straight forward after the install_production.sh script

**Comment by enoch85** [comment]
@Ark74 I improved it a bit more. 

>This sketch runs straight forward after the install_production.sh script

No it doesn't, it needs to be added as a function here: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L494-L577

**Comment by enoch85** [comment]
But even better would be to add it to the startup-script here: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L84 and here: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L355

**Comment by Ark74** [comment]
> No it doesn't, it needs to be added as a function here

No, i mean that on its current stage it can be (manually) run right after install_production and it will work.

Maybe this can be added to the 
* Contacts
* Calendar
* Spreed

list to be enabled or find its path the same way that collabora will.

Thanks again.

**Comment by enoch85** [comment]
We will see, the I prefer to let the user choose. I started a poll here: https://twitter.com/techandme_se/status/817044233437716480

`nextcloud_install_production.sh` is just used to prepare Nextcloud, while the startup script is run when the VM is downloaded an mounted. I plan to improve the choice there as well, so that the user can choose to install several apps at the same time. But that's for later. If you want you can copy the code from the install script and put it in the startup script and ask the user if he/she wants to install Nextant and SpreedME, collabora is not stable yet, so we'll let that be. Or have you tested the collabora script recently? Is it stable? Does it work?

Btw, join #techandme on IRC so that we can chat there.

**Pull request merged**
