### PR TITLE
move pihole update to the update script

### PR DESCRIPTION
**Pull request by szaimen**
I didn't want to add this to the nextcloud_update.sh script but because of https://github.com/nextcloud/vm/commit/16b5a6f1b73f11826ec7ee36860c5030b49e596b there is no other way.

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
This is ready 👍

**Comment by enoch85** [comment]
In that case, let's always remove the old update script without asking instead.

**Comment by enoch85** [comment]
https://github.com/nextcloud/vm/commit/862e95d9e84e24c708a606e702d69593ee7dda50

**Comment by szaimen** [comment]
Sry but I need to reopen this.
The problem isn't that you were asked if you want to download the newest update.sh script but that if you've chosen to do so it is removing the update procedure for pihole. Actually I think it is quite nice to ask to do so since there could be something manually added in there.

To fix this we can either merge this PR or remove the download of the latest update.sh from main_menu completely.

**Comment by enoch85** [comment]
The Pi-Hole script isn't one of the offifical ones, and nothing that we will consider breaking changes for it to work.

Sorry, but you have to find another way.

**Comment by szaimen** [comment]
This is superseded by #1797

**Pull request closed without merging**
