### PR TITLE
Automatically update Geoblock files

### PR DESCRIPTION
**Pull request by enoch85**
@szaimen GeoIP is your implementation, but it doesn't automatically fetch latest geofile. To solve that, I made this.

I found that https://www.miyuru.lk/geoiplegacy actually posts the month and year it's been updated, so I thought that we could scrape that info with `curl`, and then compare with the current file on the system - and that's what this change does.

Please give your opinion. Maybe there's a smarter way?

### CODE REVIEW

**Comment by enoch85** [comment]
Note to self: check connectivity before proceeding.

**Comment by enoch85** [comment]
Tested and works, I'll merge this now!

**Comment by szaimen** [comment]
Hi @enoch85,

sorry for coming back to you. I was very busy. 

The reason why I did not implement it like this was this warning on https://www.miyuru.lk/geoiplegacy:
image
So I used Github as a relay basically.

**Comment by szaimen** [comment]
Btw, yesterday was my server automatically updated and it ran into the following issue:
image
This lead to ipv4 connections not working correctly anymore. 
So it seems like there is something wrong with your implementation.
Shall I open a bug report?

**Comment by enoch85** [comment]
> Hi @enoch85,
> 
> sorry for coming back to you so late. I was very busy.
> 
> The reason why I did not implement it like this was this warning on [image] So I used Github as a relay basically.

Valid point. I actually asked the owner of the website myself, and he's fine with it! :)

> This lead to ipv4 connections not working correctly anymore.

So the filename _has_ to be `GeoIP.dat`? I find it strange that you can't set you own name in the config...

**Comment by szaimen** [comment]
> > This lead to ipv4 connections not working correctly anymore.
> 
> So the filename _has_ to be `GeoIP.dat`? I find it strange that you can't set you own name in the config...

No, the problem is that the file that is on my system does not match the config. Somehow this got messed up after your PR...

**Comment by enoch85** [comment]
So, what's the output of:

```
ls -l /usr/share/GeoIP
cat /etc/apache2/apache2.conf
```

**Comment by szaimen** [comment]
I posted the information in the screenshot above already...

**Comment by enoch85** [comment]
Sorry... 

I'll have another look and check if we can fix it, probably an easy fix. :)

**Comment by enoch85** [comment]
Can you try to run this:

```
#!/bin/bash
source /var/scripts/fetch_lib.sh

# Get newest dat files for geoblock.sh
if grep -q "^#Geoip-block" /etc/apache2/apache2.conf
then
    if get_newest_dat_files
    then
        if grep -c GeoIP.dat /etc/apache2/apache2.conf
        then
            if [ ! -f /usr/share/GeoIP/GeoIPv4.dat ]
            then
                if download_geoip_dat 4 v4
                then
                    sed -i "s|GeoIPDBFile /usr/share/GeoIP/GeoIP.dat|GeoIPDBFile /usr/share/GeoIP/GeoIPv4.dat|g" /etc/apache2/apache2.conf
                fi
            fi
        fi
        check_command systemctl restart apache2
    fi
fi
```

**Pull request merged**
