### PR TITLE
Universe repo

### PR DESCRIPTION
**Pull request by Ark74**
Adding check for universe repository on new OS release source.list.

Fix https://github.com/nextcloud/vm/issues/590
Fix https://github.com/nextcloud/vm/issues/585

### CODE REVIEW

**Comment by enoch85** [comment]
Tested and works, but this drew my attention:

```
## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
```

**Comment by Ark74** [comment]
So, does it means that all php modules are "unsupported" then?

I recall this notice from proposed and multiverse but for universe is sort of new.
Then why is still default on other ISO images?

I see no work around it but maybe document it a little more.

**Comment by enoch85** [comment]
Actually never had this issue, but I never used the default installer either, nor Proxmox or similar.

From a security standpoint I would vote against adding this. Let's keep the PR open though and see if we can find another solution.

**Comment by Ark74** [comment]
We could remove current packages on universe, seems they are not vital to the server but those pleasant features like,
* php-imagick
* php-smbclient

Listing all packages would be a great start.

**Comment by enoch85** [comment]
Have you tried the new php-fpm branch? Maybe that will work better as the versions are specified?

**Comment by Ark74** [comment]
No, maybe at night.
What does it do? Build php-fpm? 
Sounds good, but that would require a sysadmin to maintain and  liability, wouldn't it?

**Comment by enoch85** [comment]
> What does it do? Build php-fpm?

Yes. As per requested by the community. So we will change from Apache PHP to PHP-FPM in a coming release. I think it will be 14.

The only thing you may have to finetune yourself is the amount of processes you give to php-fpm. I tested some defaults with 2 GB RAM, and it seems fine.

It's a bit faster, and not so dependent on Apache.

**Comment by enoch85** [comment]
Hmmm... from the Ubuntu Documentation:

```
In addition to the officially supported package repositories available for Ubuntu, there exist additional community-maintained repositories which add thousands more packages for potential installation. Two of the most popular are the Universe and Multiverse repositories. These repositories are not officially supported by Ubuntu, but because they are maintained by the community they generally provide packages which are safe for use with your Ubuntu computer. 
```

**Comment by Ark74** [comment]
This list is not complete of all packages but gives an idea of what comes from universe,

```
adminer |    4.6.2-1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
apt-show-versions | 0.22.7ubuntu1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
coturn | 4.5.0.7-1ubuntu2 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
fail2ban |   0.10.2-2 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
figlet |    2.2.5-3 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
iptables-persistent | 1.0.4+nmu2 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
libapache2-mod-evasive |   1.10.1-3 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
libapache2-mod-qos | 11.44-1build1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
libauthen-pam-perl | 0.16-3build5 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
php-imagick | 3.4.3~rc2-2ubuntu4 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
php-redis | 3.1.6-1build1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
php-smbclient | 0.8.0-3build2 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
php7.2-imap | 7.2.7-0ubuntu0.18.04.2 | http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
php7.2-intl | 7.2.7-0ubuntu0.18.04.2 | http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
php7.2-mbstring | 7.2.7-0ubuntu0.18.04.2 | http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
php7.2-zip | 7.2.7-0ubuntu0.18.04.2 | http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
python-pip | 9.0.1-2.3~ubuntu1 | http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
redis-server |  5:4.0.9-1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
virt-what |     1.18-2 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Comment by Ark74** [comment]
I'd like to point out that
* CODE
* Docker CE
* ES OSS / RORest

many of the packages included are development or community driven products, maybe we could give universe the same treatment.

Another idea that comes to mind is move to Debian (which may not be a easy task) but their policy on packages seems to be more consistent with support and security.

https://www.debian.org/doc/debian-policy/ch-archive#s-contrib

**Comment by Ark74** [comment]
All listed packages on the previous post are available on "main".

php7.0 though. :disappointed:

**Comment by enoch85** [comment]
> php7.0 though

Yeah, that's one of the reasons I chose Ubuntu. It's close to Debian and still easy for Linux beginners to maintain. 

Also, Ubuntu has all the latest packages and is proactive when it comes to versions. There was a great discussoon when Ubuntu 16.04 adopted PHP 7.0, many thogh that they should keep 5.6, but no - which I think is a good thing.

I still fail to understand when Universe is needed though. I never had that issue. Is it only with the main image?

**Comment by Ark74** [comment]
Universe is already on the earliest releases of the VM, hence redis-server, coturn, php7.2-imap, etc.

Ubuntu disabled universe on earliest releases for servers, so this commit is only to bring it back and avoid failure to run the installer.

El 8 de agosto de 2018 1:39:51 AM CDT, Daniel Hansson <notifications@github.com> escribió:
>> php7.0 though
>
>Yeah, that's one of the reasons I chose Ubuntu. It's close to Debian
>and still easy for Linux beginners to maintain. 
>
>Also, Ubuntu has all the latest packages and is proactive when it comes
>to versions. There was a great discussoon when Ubuntu 16.04 adopted PHP
>7.0, many thogh that they should keep 5.6, but no - which I think is a
>good thing.
>
>I still fail to understand when Universe is needed though. I never had
>that issue. Is it only with the main image?
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/vm/pull/594#issuecomment-411302563

-- 
Enviado desde dispositivo móvil. Por favor, disculpa mi brevedad.

**Comment by enoch85** [comment]
> earliest releases for servers

Do you mean like 12.04?

**Comment by Ark74** [comment]
I believe there is a confusion here.
Here are the sources.list inside the Nextcloud VM as distributed,
```
# deb cdrom:[Ubuntu-Server 18.04 LTS _Bionic Beaver_ - Release amd64 (20180426)]/ bionic main restricted

#deb cdrom:[Ubuntu-Server 18.04 LTS _Bionic Beaver_ - Release amd64 (20180426)]/ bionic main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://se.archive.ubuntu.com/ubuntu/ bionic main restricted
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://se.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://se.archive.ubuntu.com/ubuntu/ bionic universe
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic universe
deb http://se.archive.ubuntu.com/ubuntu/ bionic-updates universe
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://se.archive.ubuntu.com/ubuntu/ bionic multiverse
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://se.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://se.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
# deb-src http://se.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu bionic partner
# deb-src http://archive.canonical.com/ubuntu bionic partner

deb http://security.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
# deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
# deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse
deb http://download.webmin.com/download/repository sarge contrib
```
which for short is,

```
deb http://se.archive.ubuntu.com/ubuntu/ bionic main restricted
deb http://se.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb http://se.archive.ubuntu.com/ubuntu/ bionic universe
deb http://se.archive.ubuntu.com/ubuntu/ bionic-updates universe
deb http://se.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://se.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb http://se.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
deb http://download.webmin.com/download/repository sarge contrib
```

Here the new sources.list for 18.04,
```
deb http://archive.ubuntu.com/ubuntu bionic main
deb http://archive.ubuntu.com/ubuntu bionic-security main
deb http://archive.ubuntu.com/ubuntu bionic-updates main
```

As listed [here](https://github.com/nextcloud/vm/pull/594#issuecomment-411283417), there are packages from universe living from the beginning.

This PR just adds what was already in.

**Comment by Ark74** [comment]
For the sake of security lets use restrict it to,

```
deb http://archive.ubuntu.com/ubuntu bionic main universe
deb http://archive.ubuntu.com/ubuntu bionic-security main universe
deb http://archive.ubuntu.com/ubuntu bionic-updates main universe
```

Leaving out multiverse, backports and restricted.

**Comment by enoch85** [comment]
OK, let's do it. But the function fails for me as it tries to install universe even if it's already activated. Need to check that before merge.

**Comment by Ark74** [comment]
Tested and works.
universe-test

**Comment by enoch85** [comment]
Yup, it works!

Let's merge it!

**Pull request merged**
