### PR TITLE
add Nextcloud to description in additional_apps

### PR DESCRIPTION
**Pull request by szaimen**
@enoch85 what do you think?
fix https://github.com/nextcloud/vm/issues/1589

### CODE REVIEW

**Comment by enoch85** [comment]
Same thing again, only half menu is shown. Please have a look in this PR as well.

Thanks!

**Comment by enoch85** [comment]
I don't think we need to extend the text, it will make the menu wider, and maybe don't fit all screens

**Comment by szaimen** [comment]
I am not sure what you are experiencing here. This is how it looks like for me:
image

**Comment by szaimen** [comment]
BTW: it fits in the CLI of VMplayer without problem. So I guess this should fit anywhere.
image

**Pull request merged**
