### PR TITLE
remove TLS_INSTALL from the lib

### PR DESCRIPTION
**Pull request by szaimen**
as the title says

### CODE REVIEW

**Comment by enoch85** [comment]
Hmm, I don't remember why I added it from the beginning...

**Comment by szaimen** [comment]
> Hmm, I don't remember why I added it from the beginning...

Do you mean why you added TLS_INSTALL to the lib?

I would say most likely because of this line:
https://github.com/nextcloud/vm/blob/4a6402ebfd7c5e642091643094988db216c40fa2/lib.sh#L128
(The TLSDOMAIN variable is used only there in the lib)

**Comment by enoch85** [comment]
> (The TLSDOMAIN variable is used only there in the lib)

OK, so why isn't that in this PR? :)

And no, that's just a product of the real reason. I think it was due to that I removed or replaced some `WHATEVER=1 . curl....` I wanted to fetch the latest lib, but I don't remember why.

**Comment by enoch85** [comment]
OK, just found it: https://github.com/nextcloud/vm/pull/1025/files

This PR won't affect that as I probably just added the TLS_INSTALL due to the same reason as for SUBDOMAIN in other scripts - it should just be called when needed.

I'm fine with this. :+1:

**Pull request merged**
