### PR TITLE
Mention hyper-v machine version in the FAQ

### PR DESCRIPTION
**Pull request by oparoz**

### CODE REVIEW

**Comment by ezraholm50** [comment]
Hey oparoz,

I'll let @enoch85 merge this since he's into hyper-v, looks good! Thanks

**Comment by enoch85** [comment]
LGTM

**Comment by enoch85** [comment]
And thanks btw, keep 'em coming ;)

**Comment by oparoz** [comment]
I will let you know when I run into issues ;)

**Comment by enoch85** [comment]
Btw @ezraholm50, can you add a link to the hyper-v version that we have in the shop? Thanks!

**Pull request merged**
