### PR TITLE
add 2FA via Nextcloud Notification

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
This is ready 👍

**Comment by szaimen** [comment]
hm... seems like it is not yet completely compatible with NC21
https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/474

**Comment by enoch85** [comment]
Please let me know when it is and we'll merge it as an startup-script app app, not as a default app.

**Comment by szaimen** [comment]
> and we'll merge it as an startup-script app app, not as a default app.

Where do I add it then, in which script at which place?

**Comment by enoch85** [comment]
> in which script at which place?

I think in Nextcloud configuration as a seperate script or config in the if statement.

**Comment by szaimen** [comment]
This PR itself was successfully tested. 
Unfortunately there is still no new release of the app for NC21 but it will work with NC20.
So I guess it is up to you to decide to merge this now or in a few days.

**Comment by enoch85** [comment]
> no new release of the app for NC21 but it will work with NC20.

`lowest_compatible_nc 21`

**Comment by szaimen** [comment]
> > no new release of the app for NC21 but it will work with NC20.
> 
> `lowest_compatible_nc 21`

Actually, it would be the opposite in this case 😉
`highest_compatible_nc 20`

**Comment by enoch85** [comment]
> highest_compatible_nc 20 True :)

**Comment by szaimen** [comment]
A new release with the fix for NC21 of the 2FA Nextcloud notification app was just created.
So this is now finally ready to go :)
(if you want to test it on NC21: it is possible that the new release isn't registered on all instances because of the appstore caching)

**Comment by enoch85** [comment]
> (if you want to test it on NC21: it is possible that the new release isn't registered on all instances because of the appstore caching)

Let's wait a few days. No rush. :)

**Comment by szaimen** [comment]
This was successfully tested on a NC21 instance 👍

**Comment by enoch85** [comment]
But wait, just read the script again, this is just an app. Also it needs QR-codes and backup codes to be made, which we can't provide in the CLI "GUI". 

Isn't it better if they use the actual App Store for this?

I mean, we should only list apps that needs some extra CLI commands IMHO.

**Comment by szaimen** [comment]
> Also it needs QR-codes

No that is the 2fa totp app.

> I mean, we should only list apps that needs some extra CLI commands IMHO.

Yes, you have a point 👍

**Pull request closed without merging**
