### PR TITLE
ask if the domain is correct

### PR DESCRIPTION
**Pull request by enoch85**
@szaimen I tested this and it worked, but the first time I entered the wrong domain and the script failed ofc. We should ask if it's correct before that happens

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 yes, you are right. Shouldn't this also get changed in other places where we ask for a subdomain?

**Comment by enoch85** [comment]
Oops, I merged the other change to master. :D

**Comment by enoch85** [comment]
Here: https://github.com/nextcloud/vm/commit/20dd9543c3d9dbe0b43e52a76a708e4022d09bd2

**Comment by enoch85** [comment]
@szaimen Anything I missed?

**Comment by enoch85** [comment]
We could do the same thing for the LE Revoke stuff, but that feels a bit much... Or what do you think?

**Comment by szaimen** [comment]
> We could do the same thing for the LE Revoke stuff, but that feels a bit much... Or what do you think?

No, I think this is a good idea

**Comment by szaimen** [comment]
> @szaimen Anything I missed?

I think there is another one in bitwarden_rs...

**Comment by enoch85** [comment]
I'll fix Collabora and OnlyOffice, can you take care of the rest?

**Comment by enoch85** [comment]
I can fix everyting, just a sec.

**Comment by szaimen** [comment]
> I can fix everyting, just a sec.

Nice 🚀

**Comment by enoch85** [comment]
OK done, do you think it looks good @szaimen?

**Comment by szaimen** [comment]
I think it looks good but for revoking is the question still missing. (I think in all documentserver-scripts)
I would suggest seaching for "SUDOMAIN" to find all places

**Comment by enoch85** [comment]
Aaah, forgot about integrated.

**Comment by szaimen** [comment]
Yes, integrated was missing but there are still additional places in the other documentserver scripts, too.
(We ask around 3 times in docker and 2 times in integrated if I remember correctly)

**Comment by szaimen** [comment]
@enoch85 shall I open a new issue so that we don't forget this?

**Comment by enoch85** [comment]
Please do, or make a PR directly ;)

**Pull request merged**
