### PR TITLE
fix Apache rules

### PR DESCRIPTION
**Pull request by enoch85**
Fix https://github.com/nextcloud/vm/issues/2480

### CODE REVIEW

**Comment by parided** [comment]
After fix apache rules, when install nextcloud from script nextcloud_install_production.sh, at the end of the process, when nextcloud is ready, in the log section, it report to me: 



Errore | core | OCP\Files\NotFoundException: /appdata_ocxqb3l0vb1a/theming/global
-- | -- | --

**Comment by parided** [comment]
After the fix of the apache rules, when install nextcloud from script nextcloud_install_production.sh, at the end of the process, when nextcloud is ready, in the log section, it report to me:

[core] Error: OCP\Files\NotFoundException: /appdata_ocxqb3l0vb1a/theming/global at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->get()
 1. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 72
    call_user_func_array()
 2. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 149
    OC\Files\Node\LazyFolder->__call()
 3. /var/www/nextcloud/lib/private/Files/AppData/AppData.php line 132
    OC\Files\Node\LazyFolder->get()
 4. /var/www/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php line 168
    OC\Files\AppData\AppData->getFolder()
 5. /var/www/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php line 100
    OCA\Theming\Jobs\MigrateBackgroundImages->storeUserIdsToProcess()
 6. /var/www/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php line 79
    OCA\Theming\Jobs\MigrateBackgroundImages->runPreparation()
 7. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
    OCA\Theming\Jobs\MigrateBackgroundImages->run()
 8. /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 57
    OCP\BackgroundJob\Job->start()
 9. /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 47
    OCP\BackgroundJob\QueuedJob->start()
10. /var/www/nextcloud/cron.php line 152
    OCP\BackgroundJob\QueuedJob->execute()

**Comment by enoch85** [comment]
@parided Please open a new issue in nextcloud/server.

**Comment by parided** [comment]
Ok, I open Issue #38114

**Pull request merged**
