### PR TITLE
add APCu

### PR DESCRIPTION
**Pull request by enoch85**
Needs extensive testing before merging.

cc @kesselb as you proposed it.

Just grabbed some random config, and that doesn't seem to work. Maybe something totally different is optimal for Nextcloud?

Check here for further tweaks: https://www.php.net/manual/en/apc.configuration.php

If merged, it's a fix for https://github.com/nextcloud/vm/issues/917

### CODE REVIEW

**Comment by kesselb** [comment]
I would go with the [default configuration](https://www.php.net/manual/en/apcu.configuration.php) as a start. We can always tweak it later.

**Comment by enoch85** [comment]
@kesselb Ready for testing. :)

**Comment by enoch85** [comment]
Been testing it for a while now in all possible ways. I feel confident. Added to both my clouds, and it seems faster in thumbnail loading.

**MERGE**

**Comment by kesselb** [comment]
Where can I grap the latest vm?

**Comment by enoch85** [comment]
> Where can I grap the latest vm?

I can make one for you :)

**Comment by enoch85** [comment]
@kesselb Here you go: https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N?path=%2FTESTING 

I kept both versions so that you can compare the difference. Would be interesting if you did some real benchmarking.

**Comment by enoch85** [comment]
@kesselb Did you have any time to test yet?

**Comment by kesselb** [comment]
Unfortunately not. "Nextcloud_VM_www.hanssonit.se_17.0.0b2_APCu_TESTING" does not come with apcu :thinking:

**Comment by enoch85** [comment]
Hmm, need to make a new release.

**Comment by enoch85** [comment]
@kesselb New release is out! Same URL.

**Pull request merged**
