### PR TITLE
definitely fix the onlyoffice install error

### LINKED ISSUE #1114: install onlyoffice "something got wrong during the installation...."
## Steps to reproduce
1.A fresh install of my vm nextcloud (vm downloaded fromm t&m hanson)
2.I launch the script for installing onlyoffice
3 Everything seems to be OK because It say to me: .onlyoffice was succefully installed. I press Ok, and after a message say "something got wrong during the installation....."

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)
18.0.1
**Server OS** (Ubuntu server is default)
ubuntu 18.04
**How did you install the VM?** (Scripted install from master **OR** Released version)
script
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```
the log file is empty
#### Installation log (command output)
```
Insert the CLI output here
```

### PR DESCRIPTION
**Pull request by szaimen**
fix #1114

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 Please merge this only if 18.0.2 is released. Then for most people the installations is still possible. Only for a few people wo have a connection that is slower than 2mb/s it will not work.
I'm sorry for overseeing this!

**Comment by enoch85** [comment]
We have `git_apply_patch` ;)

Just tested and it doesn't work because the it include tests, but this works:

`git apply --exclude=tests/lib/InstallerTest.php /tmp/19439.patch`

**Comment by szaimen** [comment]
ah, didn't know, that we have this :D

**Comment by enoch85** [comment]
Let's merge this now, 18.0.2 is released in two days, and this will urge people to upgrade once out.

**Pull request merged**
