### PR TITLE
fix issue with grub-probe

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>
fix https://github.com/nextcloud/vm/issues/1694

### CODE REVIEW

**Comment by szaimen** [comment]
https://github.com/nextcloud/vm/pull/1695/files#diff-67bceb0888b398c45857e1bc41f753da1a696075ff08b9b82f8136bc6af0139aR40-R85

**Comment by enoch85** [comment]
Great fix, but I'm not sure we want to mess with kernel *defaults*.

Which downside does this bring?

**Comment by szaimen** [comment]
> Which downside does this bring?

As I've written here: https://github.com/nextcloud/vm/issues/1694#issuecomment-732373150

> **Translation:** _If this variable is added with true, a renewed check for other operating systems on the PC is suppressed during an update grub. This means that only the kernel images contained in the /boot directory and your own scripts are recorded in the Grub menu according to the numbering._

**Comment by enoch85** [comment]
Hmm sorry missed that.

Let's leave it as is then. We would want the latest stuff right?

**Comment by szaimen** [comment]
> Let's leave it as is then. We would want the latest stuff right?

Hm... since this issue only appears when the snapshot exists and this fix only gets applied if the snapshot exists, I would say that this fix is fine. 

This is the only reliable way to fix #1694 so I guess it is up to you to decide what to do with this PR.

**Comment by enoch85** [comment]
I've investigated. Let's not do this.

Thanks for the PR anyway. :+1:

**Pull request closed without merging**
