### PR TITLE
fix race condition

### PR DESCRIPTION
**Pull request by enoch85**
if the path is set but the file doen't exist, it just keeps on searching, this fixes that issue.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
makes sense

question: shouldn't we break the loop directly after executing`find_log`?

**Comment by enoch85** [comment]
> question: shouldn't we break the loop directly after executingfind_log?

Hmm, might have over looked that.

Will do some testing soon.

**Comment by enoch85** [comment]
> question: shouldn't we break the loop directly after executingfind_log?

Just checked, it's already in the function.

**Comment by szaimen** [comment]
> Just checked, it's already in the function.

No, it isn't. Return doesn't break the loop, afaik.
The break must be outside of the function to work.

**Pull request merged**
