### PR TITLE
Enforce the correct OpenPGP pubkey for verification

### PR DESCRIPTION
**Pull request by ypid**
Closes: #11 
Follows good example from: https://github.com/nextcloud/docker/blob/master/Dockerfile
Related to: https://github.com/nextcloud/server/issues/755

Note, I have not tested the script. Ref: https://github.com/owncloud/vm/issues/46

Also includes the OpenPGP key in the vm:

> How would the GPG key be useful after the build is done? I don't see any usecase for it. Even you deleted the whole folder in you code.

The key needs basically no space and is useful for the mentioned reasons. Refs:

* https://github.com/nextcloud/vm/pull/19/commits/78c1f3f1374b6e8f9fc180016e1450afab52f2d8

### CODE REVIEW

**Comment by enoch85** [comment]
@ezraholm50 Please test this if you have time. Thanks!

**Comment by enoch85** [comment]
Seems legit. Will merge this.

**Comment by enoch85** [comment]
FYI @ypid 

```
gpg: directory `/home/ncadmin/.gnupg' created
gpg: new configuration file `/home/ncadmin/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/ncadmin/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/ncadmin/.gnupg/secring.gpg' created
gpg: keyring `/home/ncadmin/.gnupg/pubring.gpg' created
gpg: requesting key A724937A from hkp server ha.pool.sks-keyservers.net
gpg: /home/ncadmin/.gnupg/trustdb.gpg: trustdb created
gpg: key A724937A: public key "Nextcloud Security <security@nextcloud.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: Signature made Mon 18 Jul 2016 04:36:58 PM CEST using RSA key ID A724937A
gpg: Good signature from "Nextcloud Security <security@nextcloud.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A
```

**Comment by ypid** [comment]
Looks good to me. Thanks for merging :+1:

**Pull request merged**
