### PR TITLE
Harden fulltextsearch

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 Fulltextsearch doesn't seem to work after an reinstallation. Do you have and idea why?
If not, we will probably have to delete the option to reinstall the app and just  report to the user, that the app is already installed and doesn't support reinstalling like bitwarden.

**Comment by enoch85** [comment]
It worked before this change, so just copy what I did previously and it will work.

**Comment by szaimen** [comment]
Thanks for the tip, but actually I have copied already what you did previously and the reinstallation and the script at whole works but when I try to search for something in Nextcloud after the reinstallation, it doesn't show any result (although there are files, that should get found e.g. when searching for png or jpg)
Maybe it works in your testings?

**Comment by enoch85** [comment]
@Ark74 Do you approve these changes? Is there anything that can be made better?

Thanks!

**Comment by Ark74** [comment]
Well, if you are making a reinstallation you might wanna clean the ES db too forcing a new index, to avoid issues among installations and possible version changes.
php ~/occ fulltextsearch:reset


In case of removal/uninstall, you might wanna delete the docker volume, not only the app (ES) container.
docker stop

**Comment by enoch85** [comment]
Tested and WORKS! :D

**Comment by szaimen** [comment]
Nice! 🎉

**Pull request merged**
