### PR TITLE
Fixed issue where HTTP to HTTPS redirect leaves out the / and ultimately fails to work correctly

### PR DESCRIPTION
**Pull request by BetaLeaf**
Currently, when redirecting from HTTP to HTTPS, it fails if there is anything after $domain because it does not add back the `/`. 
Example: `http://example.com/apps/files/` redirects to `http://example.comapps/files/`
This is wrong!

I fixed it by adding the `/` on line 120.

Thanks for your time and consideration and have a great day!

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks!

Please fix this in `nextcloud_install_production.sh` as well.

**Comment by BetaLeaf** [comment]
There is nothing to fix in `nextcloud_install_production.sh` as it does not use Redirect because SSL has not yet be enabled 😉

**Comment by enoch85** [comment]
Right, forgot. Merge!

**Comment by BetaLeaf** [comment]
No problem.

**Pull request merged**
