### PR TITLE
cannot stat /etc/netplan/01-netcfg.yaml

### PR DESCRIPTION
**Pull request by ggeorgg**
On my system the file /etc/netplan/01-netcfg.yaml is not available after sudo apt install netplan.io. 
We should check if the file exists befor making a backup, otherwise the script exists without a real reason.

### CODE REVIEW

**Comment by enoch85** [comment]
Are you running Ubuntu Server 18.04?

Anyway, please do an if command instead.

**Comment by enoch85** [comment]
Sorry, saw now that it was `if`

**Comment by enoch85** [comment]
OK, so now it copies all files instead of just one.

**Comment by ggeorgg** [comment]
Yes I am using Ubuntu 18.04.1 LTS:
lsb_release -a gives me this on a new installation:
grafik
I am also surprised as you never had this problem?

Anyway, I can confirm that this commit does what it is expected to do.

**Comment by enoch85** [comment]
No I never had this issue, but this it better anyway, so thanks for your PR! :D

**Pull request merged**
