### PR TITLE
Also check $domain

### PR DESCRIPTION
**Pull request by enoch85**
Possible fix for https://github.com/nextcloud/vm/issues/163

### CODE REVIEW

**Comment by enoch85** [comment]
@flotpg can you please try this? Updated it again.

**Comment by enoch85** [comment]
@flotpg Ok, try this please.

**Comment by flotpg** [comment]
I should better comment here?
Newest update doesn't work

**Comment by enoch85** [comment]
Yes, it's better to write here. 

I think it's kind of impossible to check if a port is open behind a DMZ firewall... If you can't find a way to check it from another source..?

**Comment by flotpg** [comment]
Hm, i can check from outside fine:
nmap -sS -p 443 -O nextcloud01.ontpg.com
PORT    STATE SERVICE
443/tcp open  https

**Comment by enoch85** [comment]
Ok, fine, but how do we script that? I haven't found any way to use `nmap` from a different source. Can you help here?

**Comment by flotpg** [comment]
Haha, let me research.
There are various web-services: https://hackertarget.com/nmap-online-port-scanner

I guess it's better to ask the user if he wants to proceed if his firewall filtering heavily ;)

**Comment by flotpg** [comment]
probably you can script it with one of the services like: http://canyouseeme.org

with some ugly curl scripting ;) sorry, I'm not a coder..

**Comment by enoch85** [comment]
> I guess it's better to ask the user if he wants to proceed if his firewall filtering heavily ;)

Yeah, that seems about the right thing to do. Anyway, this is an improved check so I will merge. Thanks for letting me know about this. :)

**Comment by flotpg** [comment]
Thx for your fast help, really appreciate it. How do i get notified if there is a bypass ip/port check feature? Not urgent, i can setup let's encrypt manually.

**Comment by enoch85** [comment]
It's like if I google some day and find it. I don't think I will check for it actively as this really is a firewall "issue".

But I will remember this PR and ping you here. :)

**Comment by enoch85** [comment]
@Ark74 I fixed the issue you described as well. Please test the latest master.

**Comment by Ark74** [comment]
It's working again.
Thanks.

**Pull request merged**
