### PR TITLE
make trusted_domain removal and addition its own function

### PR DESCRIPTION
**Pull request by szaimen**
Follow up to #1989
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
@szaimen Is this ready?

**Comment by szaimen** [comment]
no, not yet

**Comment by szaimen** [comment]
Now it is ready 👍

**Comment by szaimen** [comment]
Oh, we will probably run into some issue during the startup script with that because the lib will be old and not have the new needed library. How do we handle this @enoch85 ?

**Comment by enoch85** [comment]
> Oh, we will probably run into some issue during the startup script with that because the lib will be old and not have the new needed library. How do we handle this @enoch85 ?

We wait to merge it until a new release is out

**Comment by enoch85** [comment]
Or keep the stuff that we moved to lib for now, and then remove it in the next release instead.

**Comment by szaimen** [comment]
I need to think about this

**Comment by szaimen** [comment]
I think this is the way to go. With the next release we can then simply remove the functions from each script.

**Comment by enoch85** [comment]
Will have a look at this when time allows and I'm not too tired. :)

**Pull request merged**
