### PR TITLE
only check if the fulltextsearch docker container exists

### PR DESCRIPTION
**Pull request by szaimen**
I think this check is enough

### CODE REVIEW

**Comment by enoch85** [comment]
No it's not enough, hence I added it.

**Comment by szaimen** [comment]
@enoch85 why is it not enough?

**Comment by szaimen** [comment]
BTW:
I think the check must be:
`if ! does_this_docker_exist "$nc_fts" && ! is_app_installed fulltextsearch`
no?

**Comment by enoch85** [comment]
Nope. to be sure it's never been installed before we check if either is installed, not both.

**Comment by szaimen** [comment]
Yes, problem is that this will also show the install popup if the fulltextsearch docker container is installed but the fulltextsearch app is not installed which will lead to an error during reinstallation because it cannot reinstall fulltextsearch if a container with this name already exists...
(This will not show the reinstall_remove_menu if the container exists but the fulltexsearch app is not installed what it should imo. Instead it will show the install_popup in this case which is wrong imo.)

**Comment by enoch85** [comment]
> Yes, problem is that this will also show the install popup if the fulltextsearch docker container is installed but the fulltextsearch app is not installed which will lead to an error during reinstallation because it cannot reinstall fulltextsearch if a container with this name already exists...
(This will not show the reinstall_remove_menu if the container exists but the fulltexsearch app is not installed what it should imo. Instead it will show the install_popup in this case which is wrong imo.)
This is the reason why I wamted ro change rhe check.

Much better explanation! 👍 

But, this will check if either one of those are installed (not together), and do the reinstall if that's the case, and that's what we want, right?

**Comment by szaimen** [comment]
> But, this will check if either one of those are installed (not together), and do the reinstall if that's the case, and that's what we want, right?

yes, we want that but the current check will show the install_popup and no the reinstall_remove_menu if one of those is not installed.
This is because it should be `if ! does_this_docker_exist "$nc_fts" && ! is_app_installed fulltextsearch`

**Pull request closed without merging**
