### PR TITLE
docker documentserver - don't restart docker

### PR DESCRIPTION
**Pull request by szaimen**
The restart is unnecessary here and just leads to needing to wait for the container to come online, imo.
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by enoch85** [comment]
IIRC we need to restart the docker containers for Collabora and OnlyOffice, else they won't work. 

We added for a reason anyway, I'm 100% sure of that.

**Comment by szaimen** [comment]
Okay but do we really need to restart the docker service completely?
Isn't the restart of the docker container enough?

**Comment by enoch85** [comment]
I'm fine with only restarting the container.

**Comment by szaimen** [comment]
Done 👍

**Comment by enoch85** [comment]
Perfect!

**Pull request merged**
