### PR TITLE
one small improvement to updatenotification.sh

### PR DESCRIPTION
**Pull request by szaimen**
@enoch85 this change was already tested by me so ready to go.

### CODE REVIEW

**Comment by enoch85** [comment]
OK, what does it do, and what's the difference?

**Comment by szaimen** [comment]
It just sets reportedmaj and reportedmin at the beginning to the value of currentversion.

**Comment by enoch85** [comment]
> It just sets reportedmaj and reportedmin at the beginning to the value of currentversion.

Haha yes, I can see that, but why? :D

**Comment by szaimen** [comment]
It fixes a logic error which I have forgotten in the last update to this script.
But it is only a cosmetic fix and nothing to worry about.

**Pull request merged**
