### PR TITLE
allow to install both - ONLYOFFICE and Collabora - 2

### LINKED ISSUE #1163: Install of both ONLYOFFICE and Collabora?
nextcloud_install_production.sh uninstalls ONLYOFFICE when installing Collabora, I wonder if it would be possible to have both installed by the script?

If no what are the issues preventing a simultaneous install?

### PR DESCRIPTION
**Pull request by szaimen**
Supersedes #1952
Fix #1163
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 do you have some thoughts on this?

**Comment by szaimen** [comment]
@enoch85 whats the problem here?

**Comment by enoch85** [comment]
> @enoch85 whats the problem here?

I don't like it. 

It's no playground for testing them out side by side. Either you choose Collabora or OnlyOffice.

I'm also not sure about the side effects. Just because it's possible it doesn't mean it's best practice.

**Comment by szaimen** [comment]
So then please go ahead and close the Issue and this PR since you don't want to let it happen!

**Pull request closed without merging**
