### PR TITLE
Upgrade to PostgreSQL 13

### PR DESCRIPTION
**Pull request by enoch85**
It's now supported in NC 21: https://docs.nextcloud.com/server/21/admin_manual/installation/system_requirements.html

https://www.postgresql.org/about/news/postgresql-13-released-2077/

### CODE REVIEW

**Comment by szaimen** [comment]
Are you sure about adding a 3rd party repository to the sources?
I thought better stable than bleeding edge? 😉

**Comment by enoch85** [comment]
> I thought better stable than bleeding edge? wink

It's supported by Nextcloud, so not bleeding edge IMHO.

> Are you sure about adding a 3rd party repository to the sources?

it's PostgreSQL's repo. I use it when migrating DB and it's basically the same thing as Ubuntu if not better.

What do you think?

**Comment by szaimen** [comment]
I think it is fine from a security standpoint. Question is if it might have some implications on backups/updates.

**Comment by enoch85** [comment]
Hmm, let's keep it as is. 

If one wants to upgrade it's possible, but stable stable stable or more important than "nice to have" - even if it brings some amazing futures.

Thanks for your POV.

**Pull request closed without merging**
