### PR TITLE
me

### PR DESCRIPTION
**Pull request by johnfelipe**

### CODE REVIEW

**Comment by enoch85** [comment]
Hey, thanks, but you have to make a PR from the latest master. Please also leave the "You? :)" in there.

**Comment by enoch85** [comment]
Great, thanks! Can you please also use the latest master, or at least fix the conflict?

**Comment by johnfelipe** [comment]
I do with my master branch

2017-09-21 14:33 GMT-05:00 Daniel Hansson <notifications@github.com>:

**Comment by enoch85** [comment]
Yes, but you didn't use the latest, and there where changes after that.

Do you plan to maintain this repo, or why do you want to be on the maintainers list? I mean, 1 PR doesn't count as maintaining a repo.

**Comment by johnfelipe** [comment]
I want contribute with work tested

2017-09-21 14:39 GMT-05:00 Daniel Hansson <notifications@github.com>:

**Comment by enoch85** [comment]
OK, great, then you should be on Active maintainers. I can helo you resolve the conflict this time, but next time, do a `git pull` before you commit a PR to avoid conflicts.

**Comment by enoch85** [comment]
I will merge this when you have done a few more PRs and commits to this repo.

Thank you for this, and welcome to the Nextcloud VM repo! :)

**Comment by enoch85** [comment]
@johnfelipe You ask more questions than helping me here. Sorry, I don't call that a maintainer.

**Pull request closed without merging**
